import {Component, ViewChild} from '@angular/core';
import {HttpClient} from '@angular/common/http';
import * as _ from 'lodash';
import {FormControl} from '@angular/forms';
import {Item} from './interfaces/item';
import {Result} from './interfaces/result';
import {MatTableDataSource} from '@angular/material/table';
import {MatSort} from '@angular/material/sort';
import {MatPaginator} from '@angular/material/paginator';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  silverInputFormControl = new FormControl(100000000);
  displayedColumns: string[] = ['buy', 'sell', 'profit', 'profitPerc'];
  title = 'AlbionProductFinder';
  isLoading = false;
  results: MatTableDataSource<Result>;

  private readonly baseUrl = 'https://www.albion-online-data.com/api/v1/stats/prices/';
  private readonly accessoriesUrl = `T2_CAPE,T3_CAPE,T4_CAPE,T4_CAPE@1,T4_CAPE@2,T4_CAPE@3,T5_CAPE,T5_CAPE@1,T5_CAPE@2,T5_CAPE@3,T6_CAPE,T6_CAPE@1,T6_CAPE@2,T6_CAPE@3,T7_CAPE,T7_CAPE@1,T7_CAPE@2,T7_CAPE@3,T8_CAPE,T8_CAPE@1,T8_CAPE@2,T8_CAPE@3,T4_CAPEITEM_FW_BRIDGEWATCH,T4_CAPEITEM_FW_BRIDGEWATCH@1,T4_CAPEITEM_FW_BRIDGEWATCH@2,T4_CAPEITEM_FW_BRIDGEWATCH@3,T5_CAPEITEM_FW_BRIDGEWATCH,T5_CAPEITEM_FW_BRIDGEWATCH@1,T5_CAPEITEM_FW_BRIDGEWATCH@2,T5_CAPEITEM_FW_BRIDGEWATCH@3,T6_CAPEITEM_FW_BRIDGEWATCH,T6_CAPEITEM_FW_BRIDGEWATCH@1,T6_CAPEITEM_FW_BRIDGEWATCH@2,T6_CAPEITEM_FW_BRIDGEWATCH@3,T7_CAPEITEM_FW_BRIDGEWATCH,T7_CAPEITEM_FW_BRIDGEWATCH@1,T7_CAPEITEM_FW_BRIDGEWATCH@2,T7_CAPEITEM_FW_BRIDGEWATCH@3,T8_CAPEITEM_FW_BRIDGEWATCH,T8_CAPEITEM_FW_BRIDGEWATCH@1,T8_CAPEITEM_FW_BRIDGEWATCH@2,T8_CAPEITEM_FW_BRIDGEWATCH@3,T4_CAPEITEM_FW_FORTSTERLING,T4_CAPEITEM_FW_FORTSTERLING@1,T4_CAPEITEM_FW_FORTSTERLING@2,T4_CAPEITEM_FW_FORTSTERLING@3,T5_CAPEITEM_FW_FORTSTERLING,T5_CAPEITEM_FW_FORTSTERLING@1,T5_CAPEITEM_FW_FORTSTERLING@2,T5_CAPEITEM_FW_FORTSTERLING@3,T6_CAPEITEM_FW_FORTSTERLING,T6_CAPEITEM_FW_FORTSTERLING@1,T6_CAPEITEM_FW_FORTSTERLING@2,T6_CAPEITEM_FW_FORTSTERLING@3,T7_CAPEITEM_FW_FORTSTERLING,T7_CAPEITEM_FW_FORTSTERLING@1,T7_CAPEITEM_FW_FORTSTERLING@2,T7_CAPEITEM_FW_FORTSTERLING@3,T8_CAPEITEM_FW_FORTSTERLING,T8_CAPEITEM_FW_FORTSTERLING@1,T8_CAPEITEM_FW_FORTSTERLING@2,T8_CAPEITEM_FW_FORTSTERLING@3,T4_CAPEITEM_FW_LYMHURST,T4_CAPEITEM_FW_LYMHURST@1,T4_CAPEITEM_FW_LYMHURST@2,T4_CAPEITEM_FW_LYMHURST@3,T5_CAPEITEM_FW_LYMHURST,T5_CAPEITEM_FW_LYMHURST@1,T5_CAPEITEM_FW_LYMHURST@2,T5_CAPEITEM_FW_LYMHURST@3,T6_CAPEITEM_FW_LYMHURST,T6_CAPEITEM_FW_LYMHURST@1,T6_CAPEITEM_FW_LYMHURST@2,T6_CAPEITEM_FW_LYMHURST@3,T7_CAPEITEM_FW_LYMHURST,T7_CAPEITEM_FW_LYMHURST@1,T7_CAPEITEM_FW_LYMHURST@2,T7_CAPEITEM_FW_LYMHURST@3,T8_CAPEITEM_FW_LYMHURST,T8_CAPEITEM_FW_LYMHURST@1,T8_CAPEITEM_FW_LYMHURST@2,T8_CAPEITEM_FW_LYMHURST@3,T4_CAPEITEM_FW_MARTLOCK,T4_CAPEITEM_FW_MARTLOCK@1,T4_CAPEITEM_FW_MARTLOCK@2,T4_CAPEITEM_FW_MARTLOCK@3,T5_CAPEITEM_FW_MARTLOCK,T5_CAPEITEM_FW_MARTLOCK@1,T5_CAPEITEM_FW_MARTLOCK@2,T5_CAPEITEM_FW_MARTLOCK@3,T6_CAPEITEM_FW_MARTLOCK,T6_CAPEITEM_FW_MARTLOCK@1,T6_CAPEITEM_FW_MARTLOCK@2,T6_CAPEITEM_FW_MARTLOCK@3,T7_CAPEITEM_FW_MARTLOCK,T7_CAPEITEM_FW_MARTLOCK@1,T7_CAPEITEM_FW_MARTLOCK@2,T7_CAPEITEM_FW_MARTLOCK@3,T8_CAPEITEM_FW_MARTLOCK,T8_CAPEITEM_FW_MARTLOCK@1,T8_CAPEITEM_FW_MARTLOCK@2,T8_CAPEITEM_FW_MARTLOCK@3,T4_CAPEITEM_FW_THETFORD,T4_CAPEITEM_FW_THETFORD@1,T4_CAPEITEM_FW_THETFORD@2,T4_CAPEITEM_FW_THETFORD@3,T5_CAPEITEM_FW_THETFORD,T5_CAPEITEM_FW_THETFORD@1,T5_CAPEITEM_FW_THETFORD@2,T5_CAPEITEM_FW_THETFORD@3,T6_CAPEITEM_FW_THETFORD,T6_CAPEITEM_FW_THETFORD@1,T6_CAPEITEM_FW_THETFORD@2,T6_CAPEITEM_FW_THETFORD@3,T7_CAPEITEM_FW_THETFORD,T7_CAPEITEM_FW_THETFORD@1,T7_CAPEITEM_FW_THETFORD@2,T7_CAPEITEM_FW_THETFORD@3,T8_CAPEITEM_FW_THETFORD,T8_CAPEITEM_FW_THETFORD@1`;
  private readonly armorsUrl = 'UNIQUE_SHOES_RUBBERBANDING,UNIQUE_INTERNAL_HEAD_GAMEMASTER,UNIQUE_INTERNAL_ARMOR_GAMEMASTER,UNIQUE_INTERNAL_SHOES_GAMEMASTER,T2_HEAD_PLATE_SET1,T3_HEAD_PLATE_SET1,T4_HEAD_PLATE_SET1,T4_HEAD_PLATE_SET1@1,T4_HEAD_PLATE_SET1@2,T4_HEAD_PLATE_SET1@3,T5_HEAD_PLATE_SET1,T5_HEAD_PLATE_SET1@1,T5_HEAD_PLATE_SET1@2,T5_HEAD_PLATE_SET1@3,T6_HEAD_PLATE_SET1,T6_HEAD_PLATE_SET1@1,T6_HEAD_PLATE_SET1@2,T6_HEAD_PLATE_SET1@3,T7_HEAD_PLATE_SET1,T7_HEAD_PLATE_SET1@1,T7_HEAD_PLATE_SET1@2,T7_HEAD_PLATE_SET1@3,T8_HEAD_PLATE_SET1,T8_HEAD_PLATE_SET1@1,T8_HEAD_PLATE_SET1@2,T8_HEAD_PLATE_SET1@3,T2_ARMOR_PLATE_SET1,T3_ARMOR_PLATE_SET1,T4_ARMOR_PLATE_SET1,T4_ARMOR_PLATE_SET1@1,T4_ARMOR_PLATE_SET1@2,T4_ARMOR_PLATE_SET1@3,T5_ARMOR_PLATE_SET1,T5_ARMOR_PLATE_SET1@1,T5_ARMOR_PLATE_SET1@2,T5_ARMOR_PLATE_SET1@3,T6_ARMOR_PLATE_SET1,T6_ARMOR_PLATE_SET1@1,T6_ARMOR_PLATE_SET1@2,T6_ARMOR_PLATE_SET1@3,T7_ARMOR_PLATE_SET1,T7_ARMOR_PLATE_SET1@1,T7_ARMOR_PLATE_SET1@2,T7_ARMOR_PLATE_SET1@3,T8_ARMOR_PLATE_SET1,T8_ARMOR_PLATE_SET1@1,T8_ARMOR_PLATE_SET1@2,T8_ARMOR_PLATE_SET1@3,T2_SHOES_PLATE_SET1,T3_SHOES_PLATE_SET1,T4_SHOES_PLATE_SET1,T4_SHOES_PLATE_SET1@1,T4_SHOES_PLATE_SET1@2,T4_SHOES_PLATE_SET1@3,T5_SHOES_PLATE_SET1,T5_SHOES_PLATE_SET1@1,T5_SHOES_PLATE_SET1@2,T5_SHOES_PLATE_SET1@3,T6_SHOES_PLATE_SET1,T6_SHOES_PLATE_SET1@1,T6_SHOES_PLATE_SET1@2,T6_SHOES_PLATE_SET1@3,T7_SHOES_PLATE_SET1,T7_SHOES_PLATE_SET1@1,T7_SHOES_PLATE_SET1@2,T7_SHOES_PLATE_SET1@3,T8_SHOES_PLATE_SET1,T8_SHOES_PLATE_SET1@1,T8_SHOES_PLATE_SET1@2,T8_SHOES_PLATE_SET1@3,T4_HEAD_PLATE_SET2,T4_HEAD_PLATE_SET2@1,T4_HEAD_PLATE_SET2@2,T4_HEAD_PLATE_SET2@3,T5_HEAD_PLATE_SET2,T5_HEAD_PLATE_SET2@1,T5_HEAD_PLATE_SET2@2,T5_HEAD_PLATE_SET2@3,T6_HEAD_PLATE_SET2,T6_HEAD_PLATE_SET2@1,T6_HEAD_PLATE_SET2@2,T6_HEAD_PLATE_SET2@3,T7_HEAD_PLATE_SET2,T7_HEAD_PLATE_SET2@1,T7_HEAD_PLATE_SET2@2,T7_HEAD_PLATE_SET2@3,T8_HEAD_PLATE_SET2,T8_HEAD_PLATE_SET2@1,T8_HEAD_PLATE_SET2@2,T8_HEAD_PLATE_SET2@3,T4_ARMOR_PLATE_SET2,T4_ARMOR_PLATE_SET2@1,T4_ARMOR_PLATE_SET2@2,T4_ARMOR_PLATE_SET2@3,T5_ARMOR_PLATE_SET2,T5_ARMOR_PLATE_SET2@1,T5_ARMOR_PLATE_SET2@2,T5_ARMOR_PLATE_SET2@3,T6_ARMOR_PLATE_SET2,T6_ARMOR_PLATE_SET2@1,T6_ARMOR_PLATE_SET2@2,T6_ARMOR_PLATE_SET2@3,T7_ARMOR_PLATE_SET2,T7_ARMOR_PLATE_SET2@1,T7_ARMOR_PLATE_SET2@2,T7_ARMOR_PLATE_SET2@3,T8_ARMOR_PLATE_SET2,T8_ARMOR_PLATE_SET2@1,T8_ARMOR_PLATE_SET2@2,T8_ARMOR_PLATE_SET2@3,T4_SHOES_PLATE_SET2,T4_SHOES_PLATE_SET2@1,T4_SHOES_PLATE_SET2@2,T4_SHOES_PLATE_SET2@3,T5_SHOES_PLATE_SET2,T5_SHOES_PLATE_SET2@1,T5_SHOES_PLATE_SET2@2,T5_SHOES_PLATE_SET2@3,T6_SHOES_PLATE_SET2,T6_SHOES_PLATE_SET2@1';
  private readonly artefactsUrl = 'T4_ARTEFACT_2H_ARCANESTAFF_HELL,T4_ARTEFACT_2H_BOW_HELL,T4_ARTEFACT_2H_BOW_KEEPER,T4_ARTEFACT_2H_CLEAVER_HELL,T4_ARTEFACT_2H_COMBATSTAFF_MORGANA,T4_ARTEFACT_2H_CROSSBOWLARGE_MORGANA,T4_ARTEFACT_2H_CURSEDSTAFF_MORGANA,T5_ARTEFACT_2H_CURSEDSTAFF_MORGANA,T6_ARTEFACT_2H_CURSEDSTAFF_MORGANA,T7_ARTEFACT_2H_CURSEDSTAFF_MORGANA,T8_ARTEFACT_2H_CURSEDSTAFF_MORGANA,T4_ARTEFACT_2H_DUALAXE_KEEPER,T4_ARTEFACT_2H_DUALCROSSBOW_HELL,T4_ARTEFACT_2H_DUALHAMMER_HELL,T4_ARTEFACT_2H_DUALSCIMITAR_UNDEAD,T4_ARTEFACT_2H_DUALSICKLE_UNDEAD,T4_ARTEFACT_2H_ENIGMATICORB_MORGANA,T4_ARTEFACT_2H_FIRESTAFF_HELL,T4_ARTEFACT_2H_HALBERD_MORGANA,T4_ARTEFACT_2H_HAMMER_UNDEAD,T4_ARTEFACT_2H_HARPOON_HELL,T4_ARTEFACT_MAIN_HOLYSTAFF_MORGANA,T4_ARTEFACT_2H_HOLYSTAFF_HELL,T4_ARTEFACT_2H_HOLYSTAFF_UNDEAD,T4_ARTEFACT_2H_ICECRYSTAL_UNDEAD,T4_ARTEFACT_2H_ICEGAUNTLETS_HELL,T4_ARTEFACT_2H_INFERNOSTAFF_MORGANA,T4_ARTEFACT_2H_IRONGAUNTLETS_HELL,T4_ARTEFACT_2H_LONGBOW_UNDEAD,T4_ARTEFACT_2H_MACE_MORGANA,T4_ARTEFACT_2H_NATURESTAFF_HELL,T4_ARTEFACT_2H_NATURESTAFF_KEEPER,T4_ARTEFACT_2H_RAM_KEEPER,T4_ARTEFACT_2H_REPEATINGCROSSBOW_UNDEAD,T4_ARTEFACT_2H_ROCKSTAFF_KEEPER,T4_ARTEFACT_2H_SKULLORB_HELL,T4_ARTEFACT_2H_TRIDENT_UNDEAD,T4_ARTEFACT_2H_TWINSCYTHE_HELL,T4_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD,T4_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD,T4_ARTEFACT_MAIN_FIRESTAFF_KEEPER,T4_ARTEFACT_MAIN_FROSTSTAFF_KEEPER,T4_ARTEFACT_MAIN_MACE_HELL,T4_ARTEFACT_MAIN_NATURESTAFF_KEEPER,T4_ARTEFACT_MAIN_RAPIER_MORGANA,T4_ARTEFACT_MAIN_ROCKMACE_KEEPER,T4_ARTEFACT_MAIN_SCIMITAR_MORGANA,T4_ARTEFACT_MAIN_SPEAR_KEEPER,T5_ARTEFACT_2H_ARCANESTAFF_HELL,T5_ARTEFACT_2H_BOW_HELL,T5_ARTEFACT_2H_BOW_KEEPER,T5_ARTEFACT_2H_CLEAVER_HELL,T5_ARTEFACT_2H_COMBATSTAFF_MORGANA,T5_ARTEFACT_2H_CROSSBOWLARGE_MORGANA,T5_ARTEFACT_2H_DUALAXE_KEEPER,T5_ARTEFACT_2H_DUALCROSSBOW_HELL,T5_ARTEFACT_2H_DUALHAMMER_HELL,T5_ARTEFACT_2H_DUALSCIMITAR_UNDEAD,T5_ARTEFACT_2H_DUALSICKLE_UNDEAD,T5_ARTEFACT_2H_ENIGMATICORB_MORGANA,T5_ARTEFACT_2H_FIRESTAFF_HELL,T5_ARTEFACT_2H_HALBERD_MORGANA,T5_ARTEFACT_2H_HAMMER_UNDEAD,T5_ARTEFACT_2H_HARPOON_HELL,T5_ARTEFACT_MAIN_HOLYSTAFF_MORGANA,T5_ARTEFACT_2H_HOLYSTAFF_HELL,T5_ARTEFACT_2H_HOLYSTAFF_UNDEAD,T5_ARTEFACT_2H_ICECRYSTAL_UNDEAD,T5_ARTEFACT_2H_ICEGAUNTLETS_HELL,T5_ARTEFACT_2H_INFERNOSTAFF_MORGANA,T5_ARTEFACT_2H_IRONGAUNTLETS_HELL,T5_ARTEFACT_2H_LONGBOW_UNDEAD,T5_ARTEFACT_2H_MACE_MORGANA,T5_ARTEFACT_2H_NATURESTAFF_HELL,T5_ARTEFACT_2H_NATURESTAFF_KEEPER,T5_ARTEFACT_2H_RAM_KEEPER,T5_ARTEFACT_2H_REPEATINGCROSSBOW_UNDEAD,T5_ARTEFACT_2H_ROCKSTAFF_KEEPER,T4_ARTEFACT_2H_SCYTHE_HELL,T5_ARTEFACT_2H_SCYTHE_HELL,T6_ARTEFACT_2H_SCYTHE_HELL,T7_ARTEFACT_2H_SCYTHE_HELL,T8_ARTEFACT_2H_SCYTHE_HELL,T5_ARTEFACT_2H_SKULLORB_HELL,T5_ARTEFACT_2H_TRIDENT_UNDEAD,T5_ARTEFACT_2H_TWINSCYTHE_HELL,T5_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD,T5_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD,T5_ARTEFACT_MAIN_FIRESTAFF_KEEPER,T5_ARTEFACT_MAIN_FROSTSTAFF_KEEPER,T5_ARTEFACT_MAIN_MACE_HELL,T5_ARTEFACT_MAIN_NATURESTAFF_KEEPER,T5_ARTEFACT_MAIN_RAPIER_MORGANA,T5_ARTEFACT_MAIN_ROCKMACE_KEEPER,T5_ARTEFACT_MAIN_SCIMITAR_MORGANA,T5_ARTEFACT_MAIN_SPEAR_KEEPER,T6_ARTEFACT_2H_ARCANESTAFF_HELL,T6_ARTEFACT_2H_BOW_HELL,T6_ARTEFACT_2H_BOW_KEEPER,T6_ARTEFACT_2H_CLEAVER_HELL,T6_ARTEFACT_2H_COMBATSTAFF_MORGANA,T6_ARTEFACT_2H_CROSSBOWLARGE_MORGANA,T6_ARTEFACT_2H_DUALAXE_KEEPER,T6_ARTEFACT_2H_DUALCROSSBOW_HELL,T6_ARTEFACT_2H_DUALHAMMER_HELL,T6_ARTEFACT_2H_DUALSCIMITAR_UNDEAD,T6_ARTEFACT_2H_DUALSICKLE_UNDEAD,T6_ARTEFACT_2H_ENIGMATICORB_MORGANA,T6_ARTEFACT_2H_FIRESTAFF_HELL,T6_ARTEFACT_2H_HALBERD_MORGANA,T6_ARTEFACT_2H_HAMMER_UNDEAD,T6_ARTEFACT_2H_HARPOON_HELL,T6_ARTEFACT_MAIN_HOLYSTAFF_MORGANA,T6_ARTEFACT_2H_HOLYSTAFF_HELL,T6_ARTEFACT_2H_HOLYSTAFF_UNDEAD,T6_ARTEFACT_2H_ICECRYSTAL_UNDEAD,T6_ARTEFACT_2H_ICEGAUNTLETS_HELL,T6_ARTEFACT_2H_INFERNOSTAFF_MORGANA,T6_ARTEFACT_2H_IRONGAUNTLETS_HELL,T6_ARTEFACT_2H_LONGBOW_UNDEAD';
  private readonly cityResourcesUrl = 'T1_FACTION_FOREST_TOKEN_1,T1_FACTION_HIGHLAND_TOKEN_1,T1_FACTION_STEPPE_TOKEN_1,T1_FACTION_MOUNTAIN_TOKEN_1,T1_FACTION_SWAMP_TOKEN_1';
  private readonly consumablesUrl = 'T4_SKILLBOOK_STANDARD,T1_SKILLBOOK_NONTRADABLE,T2_SKILLBOOK_NONTRADABLE,T3_SKILLBOOK_NONTRADABLE,T4_SKILLBOOK_NONTRADABLE,T5_SKILLBOOK_NONTRADABLE,T6_SKILLBOOK_NONTRADABLE,T7_SKILLBOOK_NONTRADABLE,T8_SKILLBOOK_NONTRADABLE,T3_PREMIUMITEM_3_NONTRADABLE,T1_SILVERBAG_NONTRADABLE,T2_SILVERBAG_NONTRADABLE,T3_SILVERBAG_NONTRADABLE,T4_SILVERBAG_NONTRADABLE,T5_SILVERBAG_NONTRADABLE,T6_SILVERBAG_NONTRADABLE,T7_SILVERBAG_NONTRADABLE,T8_SILVERBAG_NONTRADABLE,UNIQUE_LOOTCHEST_FIRSTREFERRAL@0,UNIQUE_LOOTCHEST_SKILLBOOKS_TELLAFRIEND@0,T4_LOOTCHEST_CRYSTAL_LEAGUE@0,T5_LOOTCHEST_CRYSTAL_LEAGUE@0,T6_LOOTCHEST_CRYSTAL_LEAGUE@0,T7_LOOTCHEST_CRYSTAL_LEAGUE@0,T8_LOOTCHEST_CRYSTAL_LEAGUE@0,UNIQUE_SKILLBOOK_ADC_GENERAL_01,UNIQUE_SILVERBAG_ADC_GENERAL_01,UNIQUE_REPAIRPOWDER_ADC_GENERAL_01,UNIQUE_FOCUSPOTION_ADC_GENERAL_01,UNIQUE_FOCUSPOTION_ADC_NONTRADABLE_01,UNIQUE_FOCUSPOTION_TUTORIAL_01,UNIQUE_LOOTCHEST_ADC_OCT2018_01@0,UNIQUE_LOOTCHEST_ADC_NOV2018@0,UNIQUE_LOOTCHEST_ADC_DEC2018@0,UNIQUE_LOOTCHEST_ADC_JAN2019@0,UNIQUE_LOOTCHEST_ADC_FEB2019@0,UNIQUE_LOOTCHEST_ADC_MAR2019@0,UNIQUE_LOOTCHEST_ADC_APR2019@0,UNIQUE_LOOTCHEST_ADC_MAY2019@0,UNIQUE_LOOTCHEST_ADC_JUN2019@0,UNIQUE_LOOTCHEST_ADC_JUL2019@0,UNIQUE_LOOTCHEST_ADC_AUG2019@0,UNIQUE_LOOTCHEST_ADC_SEP2019@0,UNIQUE_LOOTCHEST_ADC_OCT2019@0,UNIQUE_AVATARRING_ADC_NOV2018@0,UNIQUE_AVATARRING_ADC_DEC2018@0,UNIQUE_AVATARRING_ADC_JAN2019@0,UNIQUE_AVATARRING_ADC_FEB2019@0,UNIQUE_AVATARRING_ADC_MAR2019@0,UNIQUE_AVATARRING_ADC_APR2019@0,UNIQUE_AVATARRING_ADC_MAY2019@0,UNIQUE_AVATARRING_ADC_JUN2019@0,UNIQUE_AVATARRING_ADC_JUL2019@0,UNIQUE_AVATARRING_ADC_AUG2019@0,UNIQUE_AVATARRING_ADC_SEP2019@0,UNIQUE_AVATARRING_ADC_OCT2019@0,UNIQUE_AVATARRING_CHARITY_MARCH2020@0,UNIQUE_AVATARRING_ADC_TOKENLOCKED_01@0,UNIQUE_AVATARRING_ADC_TOKENLOCKED_NATURE@0,UNIQUE_AVATARRING_ADC_TOKENLOCKED_FIRE@0,UNIQUE_AVATARRING_ADC_TOKENLOCKED_ARCANE@0,UNIQUE_AVATARRING_ADC_TOKENLOCKED_SWORDS@0,UNIQUE_AVATAR_ADC_TOKENLOCKED_01@0,T8_GVGSEASONREWARD_FAMEBUFF,T7_GVGSEASONREWARD_FAMEBUFF,T6_GVGSEASONREWARD_FAMEBUFF,T5_GVGSEASONREWARD_FAMEBUFF,T4_GVGSEASONREWARD_FAMEBUFF,UNIQUE_LOOTCHEST_BATTLEMOUNT_CRYSTAL@0,UNIQUE_LOOTCHEST_BATTLEMOUNT_GOLD@0,UNIQUE_LOOTCHEST_BATTLEMOUNT_SILVER@0,UNIQUE_LOOTCHEST_BATTLEMOUNT_BRONZE@0,UNIQUE_AVATARRING_GVGSEASONREWARD_1ST@0,UNIQUE_AVATARRING_GVGSEASONREWARD_2ND@0,UNIQUE_AVATARRING_GVGSEASONREWARD_3RD@0,UNIQUE_AVATARRING_GVGSEASONREWARD_CRYSTAL@0,UNIQUE_AVATARRING_GVGSEASONREWARD_GOLD@0,UNIQUE_AVATARRING_GVGSEASONREWARD_SILVER@0,UNIQUE_AVATARRING_GVGSEASONREWARD_BRONZE@0,UNIQUE_AVATARRING_GVGSEASONREWARD_IRON@0,UNIQUE_AVATARRING_GVGSEASONREWARD_AVALON_INVASION@0,UNIQUE_AVATARRING_TELLAFRIEND@0,UNIQUE_AVATARRING_ORIGINAL_PLAYER@0,UNIQUE_AVATAR_GVGSEASON_04@0,UNIQUE_AVATAR_GVGSEASON_05@0,UNIQUE_AVATAR_GVGSEASON_06@0,UNIQUE_AVATAR_GVGSEASON_07@0,UNIQUE_AVATAR_GVGSEASON_AVALON_INVASION@0,UNIQUE_AVATAR_GVGSEASON_08@0,UNIQUE_AVATAR_GVGSEASON_09@0,UNIQUE_AVATAR_GVGSEASON_10@0,UNIQUE_AVATAR_GVGSEASON_11@0,UNIQUE_AVATAR_GVGSEASON_12@0,T6_RANDOM_DUNGEON_ELITE_TOKEN_1,T7_RANDOM_DUNGEON_ELITE_TOKEN_1,T8_RANDOM_DUNGEON_ELITE_TOKEN_1,T6_RANDOM_DUNGEON_ELITE_TOKEN_2@1,T7_RANDOM_DUNGEON_ELITE_TOKEN_2@1,T8_RANDOM_DUNGEON_ELITE_TOKEN_2@1,T6_RANDOM_DUNGEON_ELITE_TOKEN_3@2,T7_RANDOM_DUNGEON_ELITE_TOKEN_3@2,T8_RANDOM_DUNGEON_ELITE_TOKEN_3@2,T6_RANDOM_DUNGEON_ELITE_TOKEN_4@3,T7_RANDOM_DUNGEON_ELITE_TOKEN_4@3,T8_RANDOM_DUNGEON_ELITE_TOKEN_4@3,T4_RANDOM_DUNGEON_SOLO_TOKEN_1,T5_RANDOM_DUNGEON_SOLO_TOKEN_1,T6_RANDOM_DUNGEON_SOLO_TOKEN_1,T7_RANDOM_DUNGEON_SOLO_TOKEN_1,T8_RANDOM_DUNGEON_SOLO_TOKEN_1,T4_RANDOM_DUNGEON_SOLO_TOKEN_2@1,T5_RANDOM_DUNGEON_SOLO_TOKEN_2@1,T6_RANDOM_DUNGEON_SOLO_TOKEN_2@1,T7_RANDOM_DUNGEON_SOLO_TOKEN_2@1,T8_RANDOM_DUNGEON_SOLO_TOKEN_2@1,T4_RANDOM_DUNGEON_SOLO_TOKEN_3@2,T5_RANDOM_DUNGEON_SOLO_TOKEN_3@2,T6_RANDOM_DUNGEON_SOLO_TOKEN_3@2,T7_RANDOM_DUNGEON_SOLO_TOKEN_3@2,T8_RANDOM_DUNGEON_SOLO_TOKEN_3@2';

  constructor(
    private readonly httpClient: HttpClient
  ) {}

  onButtonClick(): void {
    if (this.isLoading) {
      return;
    }
    if (!this.silverInputFormControl.value) {
      this.silverInputFormControl.patchValue(100000000);
    }
    this.isLoading = true;
    this.httpClient.get<Item[]>(this.baseUrl + this.accessoriesUrl + ',' + this.armorsUrl).subscribe(items => {
      this.isLoading = false;
      this.results = new MatTableDataSource(this.evaluateResults(items));
      this.results.sort = this.sort;
      this.results.paginator = this.paginator;
    });
  }

  private evaluateResults(items: Item[]): Result[] {
    const maxTotSilver = this.silverInputFormControl.value;
    const groupedByItemId = _.groupBy(items, 'item_id');
    const ranking: Result[] = [];
    Object.keys(groupedByItemId).forEach(itemId => {
      const entries = groupedByItemId[itemId];
      let currentHighestBuyPrice: Item;
      let currentLowestSell: Item;
      entries.forEach(entry => {
        const entryBuyPriceMax = entry.buy_price_max;
        const isEntryBuyPriceMaxAcceptable = entryBuyPriceMax !== 0 &&
          (!currentHighestBuyPrice || entryBuyPriceMax > currentHighestBuyPrice.buy_price_max);
        if (isEntryBuyPriceMaxAcceptable) {
          currentHighestBuyPrice = entry;
        }
        const entrySellPriceMin = entry.sell_price_min;
        const isEntrySellPriceMinAcceptable = entrySellPriceMin !== 0 &&
          entrySellPriceMin <= maxTotSilver &&
          (!currentLowestSell || entrySellPriceMin < currentLowestSell.sell_price_min);
        if (isEntrySellPriceMinAcceptable) {
          currentLowestSell = entry;
        }
      });
      if (!currentHighestBuyPrice || !currentLowestSell) {
        return;
      }
      const sellPriceMin = currentLowestSell.sell_price_min;
      const profit = currentHighestBuyPrice.buy_price_max - sellPriceMin;
      ranking.push({
        buy: currentLowestSell,
        sell: currentHighestBuyPrice,
        profit,
        profitPerc: profit / sellPriceMin * 100
      });
    });
    return _.sortBy(ranking, 'profitPerc').reverse();
  }
}
