import {Component, OnInit, ViewChild} from '@angular/core';
import {MatSort} from '@angular/material/sort';
import {MatPaginator} from '@angular/material/paginator';
import {FormControl, FormGroup} from '@angular/forms';
import {ItemType} from '../../interfaces/item-type';
import {MatTableDataSource} from '@angular/material/table';
import {Result} from '../../interfaces/result';
import {HttpClient} from '@angular/common/http';
import {Item} from '../../interfaces/item';
import * as _ from 'lodash';
import {City} from '../../interfaces/city';
import {distinctUntilChanged, map} from 'rxjs/operators';

@Component({
  selector: 'app-search',
  template: `
    <small><i class="data-project-banner">Prices are provided by the <a href="https://www.albion-online-data.com/" target="_blank">Albion
      Online Data Project</a></i></small>
    <div [ngClass]="{ 'with-results': !!results }" class="search-form">
      <div class="first-row">
        <mat-form-field class="buy-at-control">
          <mat-label>Where do you want to buy?</mat-label>
          <mat-select [formControl]="searchForm.controls.buyAt">
            <mat-option *ngFor="let city of cities" [value]="city">{{city}}</mat-option>
          </mat-select>
        </mat-form-field>
        <mat-form-field class="sell-at-control">
          <mat-label>Where do you want to sell?</mat-label>
          <mat-select [formControl]="searchForm.controls.sellAt">
            <mat-option *ngFor="let city of cities" [value]="city">{{city}}</mat-option>
          </mat-select>
        </mat-form-field>
        <mat-checkbox color="primary" [formControl]="searchForm.controls.filterByLocation">Filter by location</mat-checkbox>
      </div>
      <div class="second-row">
        <mat-form-field>
          <mat-label>Type</mat-label>
          <mat-select [formControl]="searchForm.controls.itemType">
            <mat-option *ngFor="let itemType of itemTypes" [value]="itemType">{{itemType}}</mat-option>
          </mat-select>
        </mat-form-field>
        <div class="silver-form-control">
          <mat-form-field>
            <mat-label>Max price? (silver)</mat-label>
            <input [formControl]="searchForm.controls.silver" matInput placeholder="Max price" type="number">
          </mat-form-field>
          <button mat-icon-button (click)="onButtonClick()" [disabled]="isLoading">
            <mat-icon>search</mat-icon>
          </button>
        </div>
      </div>
    </div>

    <div [ngClass]="{ visible: !!results }" class="results">
      <table mat-table [dataSource]="results" matSort>

        <ng-container matColumnDef="buy">
          <th mat-header-cell *matHeaderCellDef>Buy</th>
          <td mat-cell *matCellDef="let element">
            <app-item [itemCity]="element.buy.city" [itemId]="element.buy.item_id" [itemPriceDate]="element.buy.sell_price_min_date"
                      [itemPrice]="element.buy.sell_price_min" [itemName]="element.buy.name"></app-item>
          </td>
        </ng-container>

        <ng-container matColumnDef="sell">
          <th mat-header-cell *matHeaderCellDef>Sell</th>
          <td mat-cell *matCellDef="let element">
            <app-item [itemCity]="element.sell.city" [itemId]="element.sell.item_id" [itemPriceDate]="element.sell.buy_price_max_date"
                      [itemPrice]="element.sell.buy_price_max" [itemName]="element.sell.name"></app-item>
          </td>
        </ng-container>

        <ng-container matColumnDef="profit">
          <th mat-header-cell *matHeaderCellDef mat-sort-header>Profit</th>
          <td mat-cell *matCellDef="let element">
            <div class="font-bold">{{element.profit | currency: 'USD'}}</div>
          </td>
        </ng-container>

        <ng-container matColumnDef="profitPerc">
          <th mat-header-cell *matHeaderCellDef mat-sort-header>Profit %</th>
          <td mat-cell *matCellDef="let element" class="font-bold">
            <div class="font-bold">{{(element.profitPerc | number: '.2') + '%'}}</div>
          </td>
        </ng-container>

        <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
        <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
      </table>
      <mat-paginator [pageSizeOptions]="[25, 50, 100]" showFirstLastButtons></mat-paginator>
    </div>
  `,
  styleUrls: ['./search.component.scss']
})
export class SearchComponent implements OnInit {

  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  searchForm = new FormGroup({
    silver: new FormControl(100000000),
    itemType: new FormControl(ItemType.Accessories),
    buyAt: new FormControl(City.FortSterling),
    sellAt: new FormControl(City.BlackMarket),
    filterByLocation: new FormControl(true)
  });
  displayedColumns: string[] = ['buy', 'sell', 'profit', 'profitPerc'];
  itemTypes = Object.values(ItemType);
  cities = Object.values(City);
  isLoading = false;
  results: MatTableDataSource<Result>;

  private readonly baseUrl = 'https://www.albion-online-data.com/api/v1/stats/prices/';
  private readonly accessoriesUrl = `T2_CAPE,T3_CAPE,T4_CAPE,T4_CAPE@1,T4_CAPE@2,T4_CAPE@3,T5_CAPE,T5_CAPE@1,T5_CAPE@2,T5_CAPE@3,T6_CAPE,T6_CAPE@1,T6_CAPE@2,T6_CAPE@3,T7_CAPE,T7_CAPE@1,T7_CAPE@2,T7_CAPE@3,T8_CAPE,T8_CAPE@1,T8_CAPE@2,T8_CAPE@3,T4_CAPEITEM_FW_BRIDGEWATCH,T4_CAPEITEM_FW_BRIDGEWATCH@1,T4_CAPEITEM_FW_BRIDGEWATCH@2,T4_CAPEITEM_FW_BRIDGEWATCH@3,T5_CAPEITEM_FW_BRIDGEWATCH,T5_CAPEITEM_FW_BRIDGEWATCH@1,T5_CAPEITEM_FW_BRIDGEWATCH@2,T5_CAPEITEM_FW_BRIDGEWATCH@3,T6_CAPEITEM_FW_BRIDGEWATCH,T6_CAPEITEM_FW_BRIDGEWATCH@1,T6_CAPEITEM_FW_BRIDGEWATCH@2,T6_CAPEITEM_FW_BRIDGEWATCH@3,T7_CAPEITEM_FW_BRIDGEWATCH,T7_CAPEITEM_FW_BRIDGEWATCH@1,T7_CAPEITEM_FW_BRIDGEWATCH@2,T7_CAPEITEM_FW_BRIDGEWATCH@3,T8_CAPEITEM_FW_BRIDGEWATCH,T8_CAPEITEM_FW_BRIDGEWATCH@1,T8_CAPEITEM_FW_BRIDGEWATCH@2,T8_CAPEITEM_FW_BRIDGEWATCH@3,T4_CAPEITEM_FW_FORTSTERLING,T4_CAPEITEM_FW_FORTSTERLING@1,T4_CAPEITEM_FW_FORTSTERLING@2,T4_CAPEITEM_FW_FORTSTERLING@3,T5_CAPEITEM_FW_FORTSTERLING,T5_CAPEITEM_FW_FORTSTERLING@1,T5_CAPEITEM_FW_FORTSTERLING@2,T5_CAPEITEM_FW_FORTSTERLING@3,T6_CAPEITEM_FW_FORTSTERLING,T6_CAPEITEM_FW_FORTSTERLING@1,T6_CAPEITEM_FW_FORTSTERLING@2,T6_CAPEITEM_FW_FORTSTERLING@3,T7_CAPEITEM_FW_FORTSTERLING,T7_CAPEITEM_FW_FORTSTERLING@1,T7_CAPEITEM_FW_FORTSTERLING@2,T7_CAPEITEM_FW_FORTSTERLING@3,T8_CAPEITEM_FW_FORTSTERLING,T8_CAPEITEM_FW_FORTSTERLING@1,T8_CAPEITEM_FW_FORTSTERLING@2,T8_CAPEITEM_FW_FORTSTERLING@3,T4_CAPEITEM_FW_LYMHURST,T4_CAPEITEM_FW_LYMHURST@1,T4_CAPEITEM_FW_LYMHURST@2,T4_CAPEITEM_FW_LYMHURST@3,T5_CAPEITEM_FW_LYMHURST,T5_CAPEITEM_FW_LYMHURST@1,T5_CAPEITEM_FW_LYMHURST@2,T5_CAPEITEM_FW_LYMHURST@3,T6_CAPEITEM_FW_LYMHURST,T6_CAPEITEM_FW_LYMHURST@1,T6_CAPEITEM_FW_LYMHURST@2,T6_CAPEITEM_FW_LYMHURST@3,T7_CAPEITEM_FW_LYMHURST,T7_CAPEITEM_FW_LYMHURST@1,T7_CAPEITEM_FW_LYMHURST@2,T7_CAPEITEM_FW_LYMHURST@3,T8_CAPEITEM_FW_LYMHURST,T8_CAPEITEM_FW_LYMHURST@1,T8_CAPEITEM_FW_LYMHURST@2,T8_CAPEITEM_FW_LYMHURST@3,T4_CAPEITEM_FW_MARTLOCK,T4_CAPEITEM_FW_MARTLOCK@1,T4_CAPEITEM_FW_MARTLOCK@2,T4_CAPEITEM_FW_MARTLOCK@3,T5_CAPEITEM_FW_MARTLOCK,T5_CAPEITEM_FW_MARTLOCK@1,T5_CAPEITEM_FW_MARTLOCK@2,T5_CAPEITEM_FW_MARTLOCK@3,T6_CAPEITEM_FW_MARTLOCK,T6_CAPEITEM_FW_MARTLOCK@1,T6_CAPEITEM_FW_MARTLOCK@2,T6_CAPEITEM_FW_MARTLOCK@3,T7_CAPEITEM_FW_MARTLOCK,T7_CAPEITEM_FW_MARTLOCK@1,T7_CAPEITEM_FW_MARTLOCK@2,T7_CAPEITEM_FW_MARTLOCK@3,T8_CAPEITEM_FW_MARTLOCK,T8_CAPEITEM_FW_MARTLOCK@1,T8_CAPEITEM_FW_MARTLOCK@2,T8_CAPEITEM_FW_MARTLOCK@3,T4_CAPEITEM_FW_THETFORD,T4_CAPEITEM_FW_THETFORD@1,T4_CAPEITEM_FW_THETFORD@2,T4_CAPEITEM_FW_THETFORD@3,T5_CAPEITEM_FW_THETFORD,T5_CAPEITEM_FW_THETFORD@1,T5_CAPEITEM_FW_THETFORD@2,T5_CAPEITEM_FW_THETFORD@3,T6_CAPEITEM_FW_THETFORD,T6_CAPEITEM_FW_THETFORD@1,T6_CAPEITEM_FW_THETFORD@2,T6_CAPEITEM_FW_THETFORD@3,T7_CAPEITEM_FW_THETFORD,T7_CAPEITEM_FW_THETFORD@1,T7_CAPEITEM_FW_THETFORD@2,T7_CAPEITEM_FW_THETFORD@3,T8_CAPEITEM_FW_THETFORD,T8_CAPEITEM_FW_THETFORD@1`;
  private readonly armorsUrl = 'UNIQUE_SHOES_RUBBERBANDING,UNIQUE_INTERNAL_HEAD_GAMEMASTER,UNIQUE_INTERNAL_ARMOR_GAMEMASTER,UNIQUE_INTERNAL_SHOES_GAMEMASTER,T2_HEAD_PLATE_SET1,T3_HEAD_PLATE_SET1,T4_HEAD_PLATE_SET1,T4_HEAD_PLATE_SET1@1,T4_HEAD_PLATE_SET1@2,T4_HEAD_PLATE_SET1@3,T5_HEAD_PLATE_SET1,T5_HEAD_PLATE_SET1@1,T5_HEAD_PLATE_SET1@2,T5_HEAD_PLATE_SET1@3,T6_HEAD_PLATE_SET1,T6_HEAD_PLATE_SET1@1,T6_HEAD_PLATE_SET1@2,T6_HEAD_PLATE_SET1@3,T7_HEAD_PLATE_SET1,T7_HEAD_PLATE_SET1@1,T7_HEAD_PLATE_SET1@2,T7_HEAD_PLATE_SET1@3,T8_HEAD_PLATE_SET1,T8_HEAD_PLATE_SET1@1,T8_HEAD_PLATE_SET1@2,T8_HEAD_PLATE_SET1@3,T2_ARMOR_PLATE_SET1,T3_ARMOR_PLATE_SET1,T4_ARMOR_PLATE_SET1,T4_ARMOR_PLATE_SET1@1,T4_ARMOR_PLATE_SET1@2,T4_ARMOR_PLATE_SET1@3,T5_ARMOR_PLATE_SET1,T5_ARMOR_PLATE_SET1@1,T5_ARMOR_PLATE_SET1@2,T5_ARMOR_PLATE_SET1@3,T6_ARMOR_PLATE_SET1,T6_ARMOR_PLATE_SET1@1,T6_ARMOR_PLATE_SET1@2,T6_ARMOR_PLATE_SET1@3,T7_ARMOR_PLATE_SET1,T7_ARMOR_PLATE_SET1@1,T7_ARMOR_PLATE_SET1@2,T7_ARMOR_PLATE_SET1@3,T8_ARMOR_PLATE_SET1,T8_ARMOR_PLATE_SET1@1,T8_ARMOR_PLATE_SET1@2,T8_ARMOR_PLATE_SET1@3,T2_SHOES_PLATE_SET1,T3_SHOES_PLATE_SET1,T4_SHOES_PLATE_SET1,T4_SHOES_PLATE_SET1@1,T4_SHOES_PLATE_SET1@2,T4_SHOES_PLATE_SET1@3,T5_SHOES_PLATE_SET1,T5_SHOES_PLATE_SET1@1,T5_SHOES_PLATE_SET1@2,T5_SHOES_PLATE_SET1@3,T6_SHOES_PLATE_SET1,T6_SHOES_PLATE_SET1@1,T6_SHOES_PLATE_SET1@2,T6_SHOES_PLATE_SET1@3,T7_SHOES_PLATE_SET1,T7_SHOES_PLATE_SET1@1,T7_SHOES_PLATE_SET1@2,T7_SHOES_PLATE_SET1@3,T8_SHOES_PLATE_SET1,T8_SHOES_PLATE_SET1@1,T8_SHOES_PLATE_SET1@2,T8_SHOES_PLATE_SET1@3,T4_HEAD_PLATE_SET2,T4_HEAD_PLATE_SET2@1,T4_HEAD_PLATE_SET2@2,T4_HEAD_PLATE_SET2@3,T5_HEAD_PLATE_SET2,T5_HEAD_PLATE_SET2@1,T5_HEAD_PLATE_SET2@2,T5_HEAD_PLATE_SET2@3,T6_HEAD_PLATE_SET2,T6_HEAD_PLATE_SET2@1,T6_HEAD_PLATE_SET2@2,T6_HEAD_PLATE_SET2@3,T7_HEAD_PLATE_SET2,T7_HEAD_PLATE_SET2@1,T7_HEAD_PLATE_SET2@2,T7_HEAD_PLATE_SET2@3,T8_HEAD_PLATE_SET2,T8_HEAD_PLATE_SET2@1,T8_HEAD_PLATE_SET2@2,T8_HEAD_PLATE_SET2@3,T4_ARMOR_PLATE_SET2,T4_ARMOR_PLATE_SET2@1,T4_ARMOR_PLATE_SET2@2,T4_ARMOR_PLATE_SET2@3,T5_ARMOR_PLATE_SET2,T5_ARMOR_PLATE_SET2@1,T5_ARMOR_PLATE_SET2@2,T5_ARMOR_PLATE_SET2@3,T6_ARMOR_PLATE_SET2,T6_ARMOR_PLATE_SET2@1,T6_ARMOR_PLATE_SET2@2,T6_ARMOR_PLATE_SET2@3,T7_ARMOR_PLATE_SET2,T7_ARMOR_PLATE_SET2@1,T7_ARMOR_PLATE_SET2@2,T7_ARMOR_PLATE_SET2@3,T8_ARMOR_PLATE_SET2,T8_ARMOR_PLATE_SET2@1,T8_ARMOR_PLATE_SET2@2,T8_ARMOR_PLATE_SET2@3,T4_SHOES_PLATE_SET2,T4_SHOES_PLATE_SET2@1,T4_SHOES_PLATE_SET2@2,T4_SHOES_PLATE_SET2@3,T5_SHOES_PLATE_SET2,T5_SHOES_PLATE_SET2@1,T5_SHOES_PLATE_SET2@2,T5_SHOES_PLATE_SET2@3,T6_SHOES_PLATE_SET2,T6_SHOES_PLATE_SET2@1';
  private readonly artefactsUrl = 'T4_ARTEFACT_2H_ARCANESTAFF_HELL,T4_ARTEFACT_2H_BOW_HELL,T4_ARTEFACT_2H_BOW_KEEPER,T4_ARTEFACT_2H_CLEAVER_HELL,T4_ARTEFACT_2H_COMBATSTAFF_MORGANA,T4_ARTEFACT_2H_CROSSBOWLARGE_MORGANA,T4_ARTEFACT_2H_CURSEDSTAFF_MORGANA,T5_ARTEFACT_2H_CURSEDSTAFF_MORGANA,T6_ARTEFACT_2H_CURSEDSTAFF_MORGANA,T7_ARTEFACT_2H_CURSEDSTAFF_MORGANA,T8_ARTEFACT_2H_CURSEDSTAFF_MORGANA,T4_ARTEFACT_2H_DUALAXE_KEEPER,T4_ARTEFACT_2H_DUALCROSSBOW_HELL,T4_ARTEFACT_2H_DUALHAMMER_HELL,T4_ARTEFACT_2H_DUALSCIMITAR_UNDEAD,T4_ARTEFACT_2H_DUALSICKLE_UNDEAD,T4_ARTEFACT_2H_ENIGMATICORB_MORGANA,T4_ARTEFACT_2H_FIRESTAFF_HELL,T4_ARTEFACT_2H_HALBERD_MORGANA,T4_ARTEFACT_2H_HAMMER_UNDEAD,T4_ARTEFACT_2H_HARPOON_HELL,T4_ARTEFACT_MAIN_HOLYSTAFF_MORGANA,T4_ARTEFACT_2H_HOLYSTAFF_HELL,T4_ARTEFACT_2H_HOLYSTAFF_UNDEAD,T4_ARTEFACT_2H_ICECRYSTAL_UNDEAD,T4_ARTEFACT_2H_ICEGAUNTLETS_HELL,T4_ARTEFACT_2H_INFERNOSTAFF_MORGANA,T4_ARTEFACT_2H_IRONGAUNTLETS_HELL,T4_ARTEFACT_2H_LONGBOW_UNDEAD,T4_ARTEFACT_2H_MACE_MORGANA,T4_ARTEFACT_2H_NATURESTAFF_HELL,T4_ARTEFACT_2H_NATURESTAFF_KEEPER,T4_ARTEFACT_2H_RAM_KEEPER,T4_ARTEFACT_2H_REPEATINGCROSSBOW_UNDEAD,T4_ARTEFACT_2H_ROCKSTAFF_KEEPER,T4_ARTEFACT_2H_SKULLORB_HELL,T4_ARTEFACT_2H_TRIDENT_UNDEAD,T4_ARTEFACT_2H_TWINSCYTHE_HELL,T4_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD,T4_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD,T4_ARTEFACT_MAIN_FIRESTAFF_KEEPER,T4_ARTEFACT_MAIN_FROSTSTAFF_KEEPER,T4_ARTEFACT_MAIN_MACE_HELL,T4_ARTEFACT_MAIN_NATURESTAFF_KEEPER,T4_ARTEFACT_MAIN_RAPIER_MORGANA,T4_ARTEFACT_MAIN_ROCKMACE_KEEPER,T4_ARTEFACT_MAIN_SCIMITAR_MORGANA,T4_ARTEFACT_MAIN_SPEAR_KEEPER,T5_ARTEFACT_2H_ARCANESTAFF_HELL,T5_ARTEFACT_2H_BOW_HELL,T5_ARTEFACT_2H_BOW_KEEPER,T5_ARTEFACT_2H_CLEAVER_HELL,T5_ARTEFACT_2H_COMBATSTAFF_MORGANA,T5_ARTEFACT_2H_CROSSBOWLARGE_MORGANA,T5_ARTEFACT_2H_DUALAXE_KEEPER,T5_ARTEFACT_2H_DUALCROSSBOW_HELL,T5_ARTEFACT_2H_DUALHAMMER_HELL,T5_ARTEFACT_2H_DUALSCIMITAR_UNDEAD,T5_ARTEFACT_2H_DUALSICKLE_UNDEAD,T5_ARTEFACT_2H_ENIGMATICORB_MORGANA,T5_ARTEFACT_2H_FIRESTAFF_HELL,T5_ARTEFACT_2H_HALBERD_MORGANA,T5_ARTEFACT_2H_HAMMER_UNDEAD,T5_ARTEFACT_2H_HARPOON_HELL,T5_ARTEFACT_MAIN_HOLYSTAFF_MORGANA,T5_ARTEFACT_2H_HOLYSTAFF_HELL,T5_ARTEFACT_2H_HOLYSTAFF_UNDEAD,T5_ARTEFACT_2H_ICECRYSTAL_UNDEAD,T5_ARTEFACT_2H_ICEGAUNTLETS_HELL,T5_ARTEFACT_2H_INFERNOSTAFF_MORGANA,T5_ARTEFACT_2H_IRONGAUNTLETS_HELL,T5_ARTEFACT_2H_LONGBOW_UNDEAD,T5_ARTEFACT_2H_MACE_MORGANA,T5_ARTEFACT_2H_NATURESTAFF_HELL,T5_ARTEFACT_2H_NATURESTAFF_KEEPER,T5_ARTEFACT_2H_RAM_KEEPER,T5_ARTEFACT_2H_REPEATINGCROSSBOW_UNDEAD,T5_ARTEFACT_2H_ROCKSTAFF_KEEPER,T4_ARTEFACT_2H_SCYTHE_HELL,T5_ARTEFACT_2H_SCYTHE_HELL,T6_ARTEFACT_2H_SCYTHE_HELL,T7_ARTEFACT_2H_SCYTHE_HELL,T8_ARTEFACT_2H_SCYTHE_HELL,T5_ARTEFACT_2H_SKULLORB_HELL,T5_ARTEFACT_2H_TRIDENT_UNDEAD,T5_ARTEFACT_2H_TWINSCYTHE_HELL,T5_ARTEFACT_MAIN_ARCANESTAFF_UNDEAD,T5_ARTEFACT_MAIN_CURSEDSTAFF_UNDEAD,T5_ARTEFACT_MAIN_FIRESTAFF_KEEPER,T5_ARTEFACT_MAIN_FROSTSTAFF_KEEPER,T5_ARTEFACT_MAIN_MACE_HELL,T5_ARTEFACT_MAIN_NATURESTAFF_KEEPER,T5_ARTEFACT_MAIN_RAPIER_MORGANA,T5_ARTEFACT_MAIN_ROCKMACE_KEEPER,T5_ARTEFACT_MAIN_SCIMITAR_MORGANA,T5_ARTEFACT_MAIN_SPEAR_KEEPER,T6_ARTEFACT_2H_ARCANESTAFF_HELL,T6_ARTEFACT_2H_BOW_HELL,T6_ARTEFACT_2H_BOW_KEEPER,T6_ARTEFACT_2H_CLEAVER_HELL,T6_ARTEFACT_2H_COMBATSTAFF_MORGANA,T6_ARTEFACT_2H_CROSSBOWLARGE_MORGANA,T6_ARTEFACT_2H_DUALAXE_KEEPER,T6_ARTEFACT_2H_DUALCROSSBOW_HELL,T6_ARTEFACT_2H_DUALHAMMER_HELL,T6_ARTEFACT_2H_DUALSCIMITAR_UNDEAD,T6_ARTEFACT_2H_DUALSICKLE_UNDEAD,T6_ARTEFACT_2H_ENIGMATICORB_MORGANA,T6_ARTEFACT_2H_FIRESTAFF_HELL,T6_ARTEFACT_2H_HALBERD_MORGANA,T6_ARTEFACT_2H_HAMMER_UNDEAD,T6_ARTEFACT_2H_HARPOON_HELL,T6_ARTEFACT_MAIN_HOLYSTAFF_MORGANA,T6_ARTEFACT_2H_HOLYSTAFF_HELL,T6_ARTEFACT_2H_HOLYSTAFF_UNDEAD,T6_ARTEFACT_2H_ICECRYSTAL_UNDEAD,T6_ARTEFACT_2H_ICEGAUNTLETS_HELL,T6_ARTEFACT_2H_INFERNOSTAFF_MORGANA,T6_ARTEFACT_2H_IRONGAUNTLETS_HELL,T6_ARTEFACT_2H_LONGBOW_UNDEAD';
  private readonly cityResourcesUrl = 'T1_FACTION_FOREST_TOKEN_1,T1_FACTION_HIGHLAND_TOKEN_1,T1_FACTION_STEPPE_TOKEN_1,T1_FACTION_MOUNTAIN_TOKEN_1,T1_FACTION_SWAMP_TOKEN_1';
  private readonly consumablesUrl = 'T4_SKILLBOOK_STANDARD,T1_SKILLBOOK_NONTRADABLE,T2_SKILLBOOK_NONTRADABLE,T3_SKILLBOOK_NONTRADABLE,T4_SKILLBOOK_NONTRADABLE,T5_SKILLBOOK_NONTRADABLE,T6_SKILLBOOK_NONTRADABLE,T7_SKILLBOOK_NONTRADABLE,T8_SKILLBOOK_NONTRADABLE,T3_PREMIUMITEM_3_NONTRADABLE,T1_SILVERBAG_NONTRADABLE,T2_SILVERBAG_NONTRADABLE,T3_SILVERBAG_NONTRADABLE,T4_SILVERBAG_NONTRADABLE,T5_SILVERBAG_NONTRADABLE,T6_SILVERBAG_NONTRADABLE,T7_SILVERBAG_NONTRADABLE,T8_SILVERBAG_NONTRADABLE,UNIQUE_LOOTCHEST_FIRSTREFERRAL@0,UNIQUE_LOOTCHEST_SKILLBOOKS_TELLAFRIEND@0,T4_LOOTCHEST_CRYSTAL_LEAGUE@0,T5_LOOTCHEST_CRYSTAL_LEAGUE@0,T6_LOOTCHEST_CRYSTAL_LEAGUE@0,T7_LOOTCHEST_CRYSTAL_LEAGUE@0,T8_LOOTCHEST_CRYSTAL_LEAGUE@0,UNIQUE_SKILLBOOK_ADC_GENERAL_01,UNIQUE_SILVERBAG_ADC_GENERAL_01,UNIQUE_REPAIRPOWDER_ADC_GENERAL_01,UNIQUE_FOCUSPOTION_ADC_GENERAL_01,UNIQUE_FOCUSPOTION_ADC_NONTRADABLE_01,UNIQUE_FOCUSPOTION_TUTORIAL_01,UNIQUE_LOOTCHEST_ADC_OCT2018_01@0,UNIQUE_LOOTCHEST_ADC_NOV2018@0,UNIQUE_LOOTCHEST_ADC_DEC2018@0,UNIQUE_LOOTCHEST_ADC_JAN2019@0,UNIQUE_LOOTCHEST_ADC_FEB2019@0,UNIQUE_LOOTCHEST_ADC_MAR2019@0,UNIQUE_LOOTCHEST_ADC_APR2019@0,UNIQUE_LOOTCHEST_ADC_MAY2019@0,UNIQUE_LOOTCHEST_ADC_JUN2019@0,UNIQUE_LOOTCHEST_ADC_JUL2019@0,UNIQUE_LOOTCHEST_ADC_AUG2019@0,UNIQUE_LOOTCHEST_ADC_SEP2019@0,UNIQUE_LOOTCHEST_ADC_OCT2019@0,UNIQUE_AVATARRING_ADC_NOV2018@0,UNIQUE_AVATARRING_ADC_DEC2018@0,UNIQUE_AVATARRING_ADC_JAN2019@0,UNIQUE_AVATARRING_ADC_FEB2019@0,UNIQUE_AVATARRING_ADC_MAR2019@0,UNIQUE_AVATARRING_ADC_APR2019@0,UNIQUE_AVATARRING_ADC_MAY2019@0,UNIQUE_AVATARRING_ADC_JUN2019@0,UNIQUE_AVATARRING_ADC_JUL2019@0,UNIQUE_AVATARRING_ADC_AUG2019@0,UNIQUE_AVATARRING_ADC_SEP2019@0,UNIQUE_AVATARRING_ADC_OCT2019@0,UNIQUE_AVATARRING_CHARITY_MARCH2020@0,UNIQUE_AVATARRING_ADC_TOKENLOCKED_01@0,UNIQUE_AVATARRING_ADC_TOKENLOCKED_NATURE@0,UNIQUE_AVATARRING_ADC_TOKENLOCKED_FIRE@0,UNIQUE_AVATARRING_ADC_TOKENLOCKED_ARCANE@0,UNIQUE_AVATARRING_ADC_TOKENLOCKED_SWORDS@0,UNIQUE_AVATAR_ADC_TOKENLOCKED_01@0,T8_GVGSEASONREWARD_FAMEBUFF,T7_GVGSEASONREWARD_FAMEBUFF,T6_GVGSEASONREWARD_FAMEBUFF,T5_GVGSEASONREWARD_FAMEBUFF,T4_GVGSEASONREWARD_FAMEBUFF,UNIQUE_LOOTCHEST_BATTLEMOUNT_CRYSTAL@0,UNIQUE_LOOTCHEST_BATTLEMOUNT_GOLD@0,UNIQUE_LOOTCHEST_BATTLEMOUNT_SILVER@0,UNIQUE_LOOTCHEST_BATTLEMOUNT_BRONZE@0,UNIQUE_AVATARRING_GVGSEASONREWARD_1ST@0,UNIQUE_AVATARRING_GVGSEASONREWARD_2ND@0,UNIQUE_AVATARRING_GVGSEASONREWARD_3RD@0,UNIQUE_AVATARRING_GVGSEASONREWARD_CRYSTAL@0,UNIQUE_AVATARRING_GVGSEASONREWARD_GOLD@0,UNIQUE_AVATARRING_GVGSEASONREWARD_SILVER@0,UNIQUE_AVATARRING_GVGSEASONREWARD_BRONZE@0,UNIQUE_AVATARRING_GVGSEASONREWARD_IRON@0,UNIQUE_AVATARRING_GVGSEASONREWARD_AVALON_INVASION@0,UNIQUE_AVATARRING_TELLAFRIEND@0,UNIQUE_AVATARRING_ORIGINAL_PLAYER@0,UNIQUE_AVATAR_GVGSEASON_04@0,UNIQUE_AVATAR_GVGSEASON_05@0,UNIQUE_AVATAR_GVGSEASON_06@0,UNIQUE_AVATAR_GVGSEASON_07@0,UNIQUE_AVATAR_GVGSEASON_AVALON_INVASION@0,UNIQUE_AVATAR_GVGSEASON_08@0,UNIQUE_AVATAR_GVGSEASON_09@0,UNIQUE_AVATAR_GVGSEASON_10@0,UNIQUE_AVATAR_GVGSEASON_11@0,UNIQUE_AVATAR_GVGSEASON_12@0,T6_RANDOM_DUNGEON_ELITE_TOKEN_1,T7_RANDOM_DUNGEON_ELITE_TOKEN_1,T8_RANDOM_DUNGEON_ELITE_TOKEN_1,T6_RANDOM_DUNGEON_ELITE_TOKEN_2@1,T7_RANDOM_DUNGEON_ELITE_TOKEN_2@1,T8_RANDOM_DUNGEON_ELITE_TOKEN_2@1,T6_RANDOM_DUNGEON_ELITE_TOKEN_3@2,T7_RANDOM_DUNGEON_ELITE_TOKEN_3@2,T8_RANDOM_DUNGEON_ELITE_TOKEN_3@2,T6_RANDOM_DUNGEON_ELITE_TOKEN_4@3,T7_RANDOM_DUNGEON_ELITE_TOKEN_4@3,T8_RANDOM_DUNGEON_ELITE_TOKEN_4@3,T4_RANDOM_DUNGEON_SOLO_TOKEN_1,T5_RANDOM_DUNGEON_SOLO_TOKEN_1,T6_RANDOM_DUNGEON_SOLO_TOKEN_1,T7_RANDOM_DUNGEON_SOLO_TOKEN_1,T8_RANDOM_DUNGEON_SOLO_TOKEN_1,T4_RANDOM_DUNGEON_SOLO_TOKEN_2@1,T5_RANDOM_DUNGEON_SOLO_TOKEN_2@1,T6_RANDOM_DUNGEON_SOLO_TOKEN_2@1,T7_RANDOM_DUNGEON_SOLO_TOKEN_2@1,T8_RANDOM_DUNGEON_SOLO_TOKEN_2@1,T4_RANDOM_DUNGEON_SOLO_TOKEN_3@2,T5_RANDOM_DUNGEON_SOLO_TOKEN_3@2,T6_RANDOM_DUNGEON_SOLO_TOKEN_3@2,T7_RANDOM_DUNGEON_SOLO_TOKEN_3@2,T8_RANDOM_DUNGEON_SOLO_TOKEN_3@2';
  private readonly farmableUrl = 'T1_FARM_CARROT_SEED,T2_FARM_BEAN_SEED,T3_FARM_WHEAT_SEED,T4_FARM_TURNIP_SEED,T5_FARM_CABBAGE_SEED,T6_FARM_POTATO_SEED,T7_FARM_CORN_SEED,T8_FARM_PUMPKIN_SEED,T2_FARM_AGARIC_SEED,T3_FARM_COMFREY_SEED,T4_FARM_BURDOCK_SEED,T5_FARM_TEASEL_SEED,T6_FARM_FOXGLOVE_SEED,T7_FARM_MULLEIN_SEED,T8_FARM_YARROW_SEED,T3_FARM_OX_BABY,T4_FARM_OX_BABY,T5_FARM_OX_BABY,T6_FARM_OX_BABY,T7_FARM_OX_BABY,T8_FARM_OX_BABY,T3_FARM_HORSE_BABY,T4_FARM_HORSE_BABY,T5_FARM_HORSE_BABY,T6_FARM_HORSE_BABY,T7_FARM_HORSE_BABY,T8_FARM_HORSE_BABY,T6_FARM_DIREWOLF_BABY,T7_FARM_DIREBOAR_BABY,T8_FARM_DIREBEAR_BABY,T7_FARM_SWAMPDRAGON_BABY,T8_FARM_MAMMOTH_BABY,T5_FARM_COUGAR_BABY,T8_FARM_DIREWOLF_BABY,T4_FARM_GIANTSTAG_BABY,T6_FARM_GIANTSTAG_BABY,T5_FARM_MOABIRD_FW_BRIDGEWATCH_BABY,T5_FARM_DIREBEAR_FW_FORTSTERLING_BABY,T5_FARM_DIREBOAR_FW_LYMHURST_BABY,T5_FARM_RAM_FW_MARTLOCK_BABY,T5_FARM_SWAMPDRAGON_FW_THETFORD_BABY,T3_FARM_CHICKEN_BABY,T4_FARM_GOAT_BABY,T5_FARM_GOOSE_BABY,T6_FARM_SHEEP_BABY,T7_FARM_PIG_BABY,T8_FARM_COW_BABY';
  private readonly fornitureUrl = 'T1_FARM_CARROT_SEED,T2_FARM_BEAN_SEED,T3_FARM_WHEAT_SEED,T4_FARM_TURNIP_SEED,T5_FARM_CABBAGE_SEED,T6_FARM_POTATO_SEED,T7_FARM_CORN_SEED,T8_FARM_PUMPKIN_SEED,T2_FARM_AGARIC_SEED,T3_FARM_COMFREY_SEED,T4_FARM_BURDOCK_SEED,T5_FARM_TEASEL_SEED,T6_FARM_FOXGLOVE_SEED,T7_FARM_MULLEIN_SEED,T8_FARM_YARROW_SEED,T3_FARM_OX_BABY,T4_FARM_OX_BABY,T5_FARM_OX_BABY,T6_FARM_OX_BABY,T7_FARM_OX_BABY,T8_FARM_OX_BABY,T3_FARM_HORSE_BABY,T4_FARM_HORSE_BABY,T5_FARM_HORSE_BABY,T6_FARM_HORSE_BABY,T7_FARM_HORSE_BABY,T8_FARM_HORSE_BABY,T6_FARM_DIREWOLF_BABY,T7_FARM_DIREBOAR_BABY,T8_FARM_DIREBEAR_BABY,T7_FARM_SWAMPDRAGON_BABY,T8_FARM_MAMMOTH_BABY,T5_FARM_COUGAR_BABY,T8_FARM_DIREWOLF_BABY,T4_FARM_GIANTSTAG_BABY,T6_FARM_GIANTSTAG_BABY,T5_FARM_MOABIRD_FW_BRIDGEWATCH_BABY,T5_FARM_DIREBEAR_FW_FORTSTERLING_BABY,T5_FARM_DIREBOAR_FW_LYMHURST_BABY,T5_FARM_RAM_FW_MARTLOCK_BABY,T5_FARM_SWAMPDRAGON_FW_THETFORD_BABY,T3_FARM_CHICKEN_BABY,T4_FARM_GOAT_BABY,T5_FARM_GOOSE_BABY,T6_FARM_SHEEP_BABY,T7_FARM_PIG_BABY,T8_FARM_COW_BABY';
  private readonly gatheringGearUrl = 'T4_HEAD_GATHERER_FIBER,T4_HEAD_GATHERER_FIBER@1,T4_HEAD_GATHERER_FIBER@2,T4_HEAD_GATHERER_FIBER@3,T5_HEAD_GATHERER_FIBER,T5_HEAD_GATHERER_FIBER@1,T5_HEAD_GATHERER_FIBER@2,T5_HEAD_GATHERER_FIBER@3,T6_HEAD_GATHERER_FIBER,T6_HEAD_GATHERER_FIBER@1,T6_HEAD_GATHERER_FIBER@2,T6_HEAD_GATHERER_FIBER@3,T7_HEAD_GATHERER_FIBER,T7_HEAD_GATHERER_FIBER@1,T7_HEAD_GATHERER_FIBER@2,T7_HEAD_GATHERER_FIBER@3,T8_HEAD_GATHERER_FIBER,T8_HEAD_GATHERER_FIBER@1,T8_HEAD_GATHERER_FIBER@2,T8_HEAD_GATHERER_FIBER@3,T4_ARMOR_GATHERER_FIBER,T4_ARMOR_GATHERER_FIBER@1,T4_ARMOR_GATHERER_FIBER@2,T4_ARMOR_GATHERER_FIBER@3,T5_ARMOR_GATHERER_FIBER,T5_ARMOR_GATHERER_FIBER@1,T5_ARMOR_GATHERER_FIBER@2,T5_ARMOR_GATHERER_FIBER@3,T6_ARMOR_GATHERER_FIBER,T6_ARMOR_GATHERER_FIBER@1,T6_ARMOR_GATHERER_FIBER@2,T6_ARMOR_GATHERER_FIBER@3,T7_ARMOR_GATHERER_FIBER,T7_ARMOR_GATHERER_FIBER@1,T7_ARMOR_GATHERER_FIBER@2,T7_ARMOR_GATHERER_FIBER@3,T8_ARMOR_GATHERER_FIBER,T8_ARMOR_GATHERER_FIBER@1,T8_ARMOR_GATHERER_FIBER@2,T8_ARMOR_GATHERER_FIBER@3,T4_SHOES_GATHERER_FIBER,T4_SHOES_GATHERER_FIBER@1,T4_SHOES_GATHERER_FIBER@2,T4_SHOES_GATHERER_FIBER@3,T5_SHOES_GATHERER_FIBER,T5_SHOES_GATHERER_FIBER@1,T5_SHOES_GATHERER_FIBER@2,T5_SHOES_GATHERER_FIBER@3,T6_SHOES_GATHERER_FIBER,T6_SHOES_GATHERER_FIBER@1,T6_SHOES_GATHERER_FIBER@2,T6_SHOES_GATHERER_FIBER@3,T7_SHOES_GATHERER_FIBER,T7_SHOES_GATHERER_FIBER@1,T7_SHOES_GATHERER_FIBER@2,T7_SHOES_GATHERER_FIBER@3,T8_SHOES_GATHERER_FIBER,T8_SHOES_GATHERER_FIBER@1,T8_SHOES_GATHERER_FIBER@2,T8_SHOES_GATHERER_FIBER@3,T4_BACKPACK_GATHERER_FIBER,T4_BACKPACK_GATHERER_FIBER@1,T4_BACKPACK_GATHERER_FIBER@2,T4_BACKPACK_GATHERER_FIBER@3,T5_BACKPACK_GATHERER_FIBER,T5_BACKPACK_GATHERER_FIBER@1,T5_BACKPACK_GATHERER_FIBER@2,T5_BACKPACK_GATHERER_FIBER@3,T6_BACKPACK_GATHERER_FIBER,T6_BACKPACK_GATHERER_FIBER@1,T6_BACKPACK_GATHERER_FIBER@2,T6_BACKPACK_GATHERER_FIBER@3,T7_BACKPACK_GATHERER_FIBER,T7_BACKPACK_GATHERER_FIBER@1,T7_BACKPACK_GATHERER_FIBER@2,T7_BACKPACK_GATHERER_FIBER@3,T8_BACKPACK_GATHERER_FIBER,T8_BACKPACK_GATHERER_FIBER@1,T8_BACKPACK_GATHERER_FIBER@2,T8_BACKPACK_GATHERER_FIBER@3,T4_HEAD_GATHERER_HIDE,T4_HEAD_GATHERER_HIDE@1,T4_HEAD_GATHERER_HIDE@2,T4_HEAD_GATHERER_HIDE@3,T5_HEAD_GATHERER_HIDE,T5_HEAD_GATHERER_HIDE@1,T5_HEAD_GATHERER_HIDE@2,T5_HEAD_GATHERER_HIDE@3,T6_HEAD_GATHERER_HIDE,T6_HEAD_GATHERER_HIDE@1,T6_HEAD_GATHERER_HIDE@2,T6_HEAD_GATHERER_HIDE@3,T7_HEAD_GATHERER_HIDE,T7_HEAD_GATHERER_HIDE@1,T7_HEAD_GATHERER_HIDE@2,T7_HEAD_GATHERER_HIDE@3,T8_HEAD_GATHERER_HIDE,T8_HEAD_GATHERER_HIDE@1,T8_HEAD_GATHERER_HIDE@2,T8_HEAD_GATHERER_HIDE@3,T4_ARMOR_GATHERER_HIDE,T4_ARMOR_GATHERER_HIDE@1,T4_ARMOR_GATHERER_HIDE@2,T4_ARMOR_GATHERER_HIDE@3,T5_ARMOR_GATHERER_HIDE,T5_ARMOR_GATHERER_HIDE@1,T5_ARMOR_GATHERER_HIDE@2,T5_ARMOR_GATHERER_HIDE@3,T6_ARMOR_GATHERER_HIDE,T6_ARMOR_GATHERER_HIDE@1,T6_ARMOR_GATHERER_HIDE@2,T6_ARMOR_GATHERER_HIDE@3,T7_ARMOR_GATHERER_HIDE,T7_ARMOR_GATHERER_HIDE@1,T7_ARMOR_GATHERER_HIDE@2,T7_ARMOR_GATHERER_HIDE@3,T8_ARMOR_GATHERER_HIDE,T8_ARMOR_GATHERER_HIDE@1,T8_ARMOR_GATHERER_HIDE@2,T8_ARMOR_GATHERER_HIDE@3';
  private readonly luxuryGoodsUrl = 'TREASURE_KNOWLEDGE_RARITY1,TREASURE_KNOWLEDGE_RARITY2,TREASURE_KNOWLEDGE_RARITY3,TREASURE_SILVERWARE_RARITY1,TREASURE_SILVERWARE_RARITY2,TREASURE_SILVERWARE_RARITY3,TREASURE_DECORATIVE_RARITY1,TREASURE_DECORATIVE_RARITY2,TREASURE_DECORATIVE_RARITY3,TREASURE_CEREMONIAL_RARITY1,TREASURE_CEREMONIAL_RARITY2,TREASURE_CEREMONIAL_RARITY3,TREASURE_TRIBAL_RARITY1,TREASURE_TRIBAL_RARITY2,TREASURE_TRIBAL_RARITY3,TREASURE_RITUAL_RARITY1,TREASURE_RITUAL_RARITY2,TREASURE_RITUAL_RARITY3,TREASURE_AVALON_RARITY1,TREASURE_AVALON_RARITY2,TREASURE_AVALON_RARITY3';
  private readonly magicUrl = 'T3_MAIN_CURSEDSTAFF,T4_MAIN_CURSEDSTAFF,T4_MAIN_CURSEDSTAFF@1,T4_MAIN_CURSEDSTAFF@2,T4_MAIN_CURSEDSTAFF@3,T5_MAIN_CURSEDSTAFF,T5_MAIN_CURSEDSTAFF@1,T5_MAIN_CURSEDSTAFF@2,T5_MAIN_CURSEDSTAFF@3,T6_MAIN_CURSEDSTAFF,T6_MAIN_CURSEDSTAFF@1,T6_MAIN_CURSEDSTAFF@2,T6_MAIN_CURSEDSTAFF@3,T7_MAIN_CURSEDSTAFF,T7_MAIN_CURSEDSTAFF@1,T7_MAIN_CURSEDSTAFF@2,T7_MAIN_CURSEDSTAFF@3,T8_MAIN_CURSEDSTAFF,T8_MAIN_CURSEDSTAFF@1,T8_MAIN_CURSEDSTAFF@2,T8_MAIN_CURSEDSTAFF@3,T4_2H_CURSEDSTAFF,T4_2H_CURSEDSTAFF@1,T4_2H_CURSEDSTAFF@2,T4_2H_CURSEDSTAFF@3,T5_2H_CURSEDSTAFF,T5_2H_CURSEDSTAFF@1,T5_2H_CURSEDSTAFF@2,T5_2H_CURSEDSTAFF@3,T6_2H_CURSEDSTAFF,T6_2H_CURSEDSTAFF@1,T6_2H_CURSEDSTAFF@2,T6_2H_CURSEDSTAFF@3,T7_2H_CURSEDSTAFF,T7_2H_CURSEDSTAFF@1,T7_2H_CURSEDSTAFF@2,T7_2H_CURSEDSTAFF@3,T8_2H_CURSEDSTAFF,T8_2H_CURSEDSTAFF@1,T8_2H_CURSEDSTAFF@2,T8_2H_CURSEDSTAFF@3,T4_2H_DEMONICSTAFF,T4_2H_DEMONICSTAFF@1,T4_2H_DEMONICSTAFF@2,T4_2H_DEMONICSTAFF@3,T5_2H_DEMONICSTAFF,T5_2H_DEMONICSTAFF@1,T5_2H_DEMONICSTAFF@2,T5_2H_DEMONICSTAFF@3,T6_2H_DEMONICSTAFF,T6_2H_DEMONICSTAFF@1,T6_2H_DEMONICSTAFF@2,T6_2H_DEMONICSTAFF@3,T7_2H_DEMONICSTAFF,T7_2H_DEMONICSTAFF@1,T7_2H_DEMONICSTAFF@2,T7_2H_DEMONICSTAFF@3,T8_2H_DEMONICSTAFF,T8_2H_DEMONICSTAFF@1,T8_2H_DEMONICSTAFF@2,T8_2H_DEMONICSTAFF@3,T4_MAIN_CURSEDSTAFF_UNDEAD,T4_MAIN_CURSEDSTAFF_UNDEAD@1,T4_MAIN_CURSEDSTAFF_UNDEAD@2,T4_MAIN_CURSEDSTAFF_UNDEAD@3,T5_MAIN_CURSEDSTAFF_UNDEAD,T5_MAIN_CURSEDSTAFF_UNDEAD@1,T5_MAIN_CURSEDSTAFF_UNDEAD@2,T5_MAIN_CURSEDSTAFF_UNDEAD@3,T6_MAIN_CURSEDSTAFF_UNDEAD,T6_MAIN_CURSEDSTAFF_UNDEAD@1,T6_MAIN_CURSEDSTAFF_UNDEAD@2,T6_MAIN_CURSEDSTAFF_UNDEAD@3,T7_MAIN_CURSEDSTAFF_UNDEAD,T7_MAIN_CURSEDSTAFF_UNDEAD@1,T7_MAIN_CURSEDSTAFF_UNDEAD@2,T7_MAIN_CURSEDSTAFF_UNDEAD@3,T8_MAIN_CURSEDSTAFF_UNDEAD,T8_MAIN_CURSEDSTAFF_UNDEAD@1,T8_MAIN_CURSEDSTAFF_UNDEAD@2,T8_MAIN_CURSEDSTAFF_UNDEAD@3,T4_2H_SKULLORB_HELL,T4_2H_SKULLORB_HELL@1,T4_2H_SKULLORB_HELL@2,T4_2H_SKULLORB_HELL@3,T5_2H_SKULLORB_HELL,T5_2H_SKULLORB_HELL@1,T5_2H_SKULLORB_HELL@2,T5_2H_SKULLORB_HELL@3,T6_2H_SKULLORB_HELL,T6_2H_SKULLORB_HELL@1,T6_2H_SKULLORB_HELL@2,T6_2H_SKULLORB_HELL@3,T7_2H_SKULLORB_HELL,T7_2H_SKULLORB_HELL@1,T7_2H_SKULLORB_HELL@2,T7_2H_SKULLORB_HELL@3,T8_2H_SKULLORB_HELL,T8_2H_SKULLORB_HELL@1,T8_2H_SKULLORB_HELL@2,T8_2H_SKULLORB_HELL@3,T4_2H_CURSEDSTAFF_MORGANA,T4_2H_CURSEDSTAFF_MORGANA@1,T4_2H_CURSEDSTAFF_MORGANA@2,T4_2H_CURSEDSTAFF_MORGANA@3,T5_2H_CURSEDSTAFF_MORGANA,T5_2H_CURSEDSTAFF_MORGANA@1,T5_2H_CURSEDSTAFF_MORGANA@2,T5_2H_CURSEDSTAFF_MORGANA@3,T6_2H_CURSEDSTAFF_MORGANA,T6_2H_CURSEDSTAFF_MORGANA@1,T6_2H_CURSEDSTAFF_MORGANA@2,T6_2H_CURSEDSTAFF_MORGANA@3,T7_2H_CURSEDSTAFF_MORGANA,T7_2H_CURSEDSTAFF_MORGANA@1,T7_2H_CURSEDSTAFF_MORGANA@2,T7_2H_CURSEDSTAFF_MORGANA@3,T8_2H_CURSEDSTAFF_MORGANA,T8_2H_CURSEDSTAFF_MORGANA@1,T8_2H_CURSEDSTAFF_MORGANA@2';
  private readonly materialsUrl = 'T6_MOUNTUPGRADE_GIANTSTAG_XMAS,UNIQUE_MOUNTUPGRADE_RAM_XMAS,T5_MOUNTUPGRADE_HORSE_CURSE,T8_MOUNTUPGRADE_HORSE_CURSE,T8_MOUNTUPGRADE_COUGAR_KEEPER,T5_MOUNTUPGRADE_HORSE_MORGANA,T8_MOUNTUPGRADE_HORSE_MORGANA,T1_SEAWEED@0,T8_FISH_SALTWATER_ALL_BOSS_SHARK@0,QUESTITEM_TOKEN_AVALON,T4_ESSENCE_POTION,T4_ESSENCE,T4_RUNE,T4_SOUL,T4_RELIC,T4_SHARD_AVALONIAN,T5_ESSENCE_POTION,T5_ESSENCE,T5_RUNE,T5_SOUL,T5_RELIC,T5_SHARD_AVALONIAN,T6_ESSENCE_POTION,T6_ESSENCE,T6_RUNE,T6_SOUL,T6_RELIC,T6_SHARD_AVALONIAN,T7_ESSENCE_POTION,T7_ESSENCE,T7_RUNE,T7_SOUL,T7_RELIC,T7_SHARD_AVALONIAN,T8_ESSENCE_POTION,T8_ESSENCE,T8_RUNE,T8_SOUL,T8_RELIC,T8_SHARD_AVALONIAN,UNIQUE_GVGTOKEN_GENERIC';
  private readonly meleeUrl = 'T3_MAIN_DAGGER,T4_MAIN_DAGGER,T4_MAIN_DAGGER@1,T4_MAIN_DAGGER@2,T4_MAIN_DAGGER@3,T5_MAIN_DAGGER,T5_MAIN_DAGGER@1,T5_MAIN_DAGGER@2,T5_MAIN_DAGGER@3,T6_MAIN_DAGGER,T6_MAIN_DAGGER@1,T6_MAIN_DAGGER@2,T6_MAIN_DAGGER@3,T7_MAIN_DAGGER,T7_MAIN_DAGGER@1,T7_MAIN_DAGGER@2,T7_MAIN_DAGGER@3,T8_MAIN_DAGGER,T8_MAIN_DAGGER@1,T8_MAIN_DAGGER@2,T8_MAIN_DAGGER@3,T4_2H_DAGGERPAIR,T4_2H_DAGGERPAIR@1,T4_2H_DAGGERPAIR@2,T4_2H_DAGGERPAIR@3,T5_2H_DAGGERPAIR,T5_2H_DAGGERPAIR@1,T5_2H_DAGGERPAIR@2,T5_2H_DAGGERPAIR@3,T6_2H_DAGGERPAIR,T6_2H_DAGGERPAIR@1,T6_2H_DAGGERPAIR@2,T6_2H_DAGGERPAIR@3,T7_2H_DAGGERPAIR,T7_2H_DAGGERPAIR@1,T7_2H_DAGGERPAIR@2,T7_2H_DAGGERPAIR@3,T8_2H_DAGGERPAIR,T8_2H_DAGGERPAIR@1,T8_2H_DAGGERPAIR@2,T8_2H_DAGGERPAIR@3,T4_2H_CLAWPAIR,T4_2H_CLAWPAIR@1,T4_2H_CLAWPAIR@2,T4_2H_CLAWPAIR@3,T5_2H_CLAWPAIR,T5_2H_CLAWPAIR@1,T5_2H_CLAWPAIR@2,T5_2H_CLAWPAIR@3,T6_2H_CLAWPAIR,T6_2H_CLAWPAIR@1,T6_2H_CLAWPAIR@2,T6_2H_CLAWPAIR@3,T7_2H_CLAWPAIR,T7_2H_CLAWPAIR@1,T7_2H_CLAWPAIR@2,T7_2H_CLAWPAIR@3,T8_2H_CLAWPAIR,T8_2H_CLAWPAIR@1,T8_2H_CLAWPAIR@2,T8_2H_CLAWPAIR@3,T4_MAIN_RAPIER_MORGANA,T4_MAIN_RAPIER_MORGANA@1,T4_MAIN_RAPIER_MORGANA@2,T4_MAIN_RAPIER_MORGANA@3,T5_MAIN_RAPIER_MORGANA,T5_MAIN_RAPIER_MORGANA@1,T5_MAIN_RAPIER_MORGANA@2,T5_MAIN_RAPIER_MORGANA@3,T6_MAIN_RAPIER_MORGANA,T6_MAIN_RAPIER_MORGANA@1,T6_MAIN_RAPIER_MORGANA@2,T6_MAIN_RAPIER_MORGANA@3,T7_MAIN_RAPIER_MORGANA,T7_MAIN_RAPIER_MORGANA@1,T7_MAIN_RAPIER_MORGANA@2,T7_MAIN_RAPIER_MORGANA@3,T8_MAIN_RAPIER_MORGANA,T8_MAIN_RAPIER_MORGANA@1,T8_MAIN_RAPIER_MORGANA@2,T8_MAIN_RAPIER_MORGANA@3,T4_2H_IRONGAUNTLETS_HELL,T4_2H_IRONGAUNTLETS_HELL@1,T4_2H_IRONGAUNTLETS_HELL@2,T4_2H_IRONGAUNTLETS_HELL@3,T5_2H_IRONGAUNTLETS_HELL,T5_2H_IRONGAUNTLETS_HELL@1,T5_2H_IRONGAUNTLETS_HELL@2,T5_2H_IRONGAUNTLETS_HELL@3,T6_2H_IRONGAUNTLETS_HELL,T6_2H_IRONGAUNTLETS_HELL@1,T6_2H_IRONGAUNTLETS_HELL@2,T6_2H_IRONGAUNTLETS_HELL@3,T7_2H_IRONGAUNTLETS_HELL,T7_2H_IRONGAUNTLETS_HELL@1,T7_2H_IRONGAUNTLETS_HELL@2,T7_2H_IRONGAUNTLETS_HELL@3,T8_2H_IRONGAUNTLETS_HELL,T8_2H_IRONGAUNTLETS_HELL@1,T8_2H_IRONGAUNTLETS_HELL@2,T8_2H_IRONGAUNTLETS_HELL@3,T4_2H_DUALSICKLE_UNDEAD,T4_2H_DUALSICKLE_UNDEAD@1,T4_2H_DUALSICKLE_UNDEAD@2,T4_2H_DUALSICKLE_UNDEAD@3,T5_2H_DUALSICKLE_UNDEAD,T5_2H_DUALSICKLE_UNDEAD@1,T5_2H_DUALSICKLE_UNDEAD@2,T5_2H_DUALSICKLE_UNDEAD@3,T6_2H_DUALSICKLE_UNDEAD,T6_2H_DUALSICKLE_UNDEAD@1,T6_2H_DUALSICKLE_UNDEAD@2,T6_2H_DUALSICKLE_UNDEAD@3,T7_2H_DUALSICKLE_UNDEAD,T7_2H_DUALSICKLE_UNDEAD@1,T7_2H_DUALSICKLE_UNDEAD@2,T7_2H_DUALSICKLE_UNDEAD@3,T8_2H_DUALSICKLE_UNDEAD,T8_2H_DUALSICKLE_UNDEAD@1,T8_2H_DUALSICKLE_UNDEAD@2';
  private readonly mountUrl = 'UNIQUE_MOUNT_ARMORED_HORSE_KNIGHT_01_TEST,T2_MOUNT_MULE,T3_MOUNT_HORSE,T4_MOUNT_HORSE,T5_MOUNT_HORSE,T6_MOUNT_HORSE,T7_MOUNT_HORSE,T8_MOUNT_HORSE,T5_MOUNT_ARMORED_HORSE,T6_MOUNT_ARMORED_HORSE,T7_MOUNT_ARMORED_HORSE,T8_MOUNT_ARMORED_HORSE,T3_MOUNT_OX,T4_MOUNT_OX,T5_MOUNT_OX,T6_MOUNT_OX,T7_MOUNT_OX,T8_MOUNT_OX,T4_MOUNT_GIANTSTAG,T6_MOUNT_DIREWOLF,T7_MOUNT_DIREBOAR,T7_MOUNT_SWAMPDRAGON,T8_MOUNT_DIREBEAR,T8_MOUNT_MAMMOTH_TRANSPORT,T5_MOUNT_MOABIRD_FW_BRIDGEWATCH,T5_MOUNT_DIREBEAR_FW_FORTSTERLING,T5_MOUNT_DIREBOAR_FW_LYMHURST,T5_MOUNT_RAM_FW_MARTLOCK,T5_MOUNT_SWAMPDRAGON_FW_THETFORD,T8_MOUNT_MAMMOTH_BATTLE@1,T7_MOUNT_SWAMPDRAGON_BATTLE,T7_MOUNT_ARMORED_SWAMPDRAGON_BATTLE,T6_MOUNT_SIEGE_BALLISTA,T8_MOUNT_HORSE_UNDEAD@1,T5_MOUNT_COUGAR_KEEPER@1,T8_MOUNT_COUGAR_KEEPER@1,T8_MOUNT_ARMORED_HORSE_MORGANA@1,UNIQUE_MOUNT_RAM_XMAS,T7_MOUNT_SWAMPDRAGON_AVALON_BASILISK,UNIQUE_MOUNT_RAM_TELLAFRIEND,UNIQUE_MOUNT_MOABIRD_TELLAFRIEND,UNIQUE_MOUNT_BAT_TELLAFRIEND,UNIQUE_MOUNT_GIANTTOAD_TELLAFRIEND,UNIQUE_MOUNT_PANDA_TELLAFRIEND,UNIQUE_MOUNT_GIANTTOAD_02_TELLAFRIEND,T5_MOUNT_ARMORED_HORSE_SKIN_01,T6_MOUNT_ARMORED_HORSE_SKIN_01,T7_MOUNT_ARMORED_HORSE_SKIN_01,T8_MOUNT_ARMORED_HORSE_SKIN_01,UNIQUE_MOUNT_BAT_PERSONAL@0,T7_MOUNT_MONITORLIZARD_ADC,T7_MOUNT_HUSKY_ADC,T6_MOUNT_FROSTRAM_ADC,T7_MOUNT_TERRORBIRD_ADC,UNIQUE_MOUNT_BEAR_KEEPER_ADC,UNIQUE_MOUNT_BLACK_PANTHER_ADC,UNIQUE_MOUNT_MORGANA_RAVEN_ADC@0,UNIQUE_MOUNT_GIANT_HORSE_ADC@0,UNIQUE_MOUNT_UNDEAD_DIREBOAR_ADC,UNIQUE_MOUNT_DIVINE_OWL_ADC@0,UNIQUE_MOUNT_HERETIC_MULE_ADC@0,UNIQUE_MOUNT_RHINO_SEASON_CRYSTAL,UNIQUE_MOUNT_RHINO_SEASON_GOLD,UNIQUE_MOUNT_RHINO_SEASON_SILVER,UNIQUE_MOUNT_RHINO_SEASON_BRONZE,UNIQUE_MOUNT_TOWER_CHARIOT_CRYSTAL,UNIQUE_MOUNT_TOWER_CHARIOT_GOLD,UNIQUE_MOUNT_TOWER_CHARIOT_SILVER,UNIQUE_MOUNT_ARMORED_EAGLE_CRYSTAL,UNIQUE_MOUNT_ARMORED_EAGLE_GOLD,UNIQUE_MOUNT_ARMORED_EAGLE_SILVER,UNIQUE_MOUNT_BEETLE_SILVER,UNIQUE_MOUNT_BEETLE_GOLD,UNIQUE_MOUNT_BEETLE_CRYSTAL,UNIQUE_MOUNT_BEHEMOTH_SILVER,UNIQUE_MOUNT_BEHEMOTH_GOLD,UNIQUE_MOUNT_BEHEMOTH_CRYSTAL,UNIQUE_MOUNT_ENT_SILVER,UNIQUE_MOUNT_ENT_GOLD,UNIQUE_MOUNT_ENT_CRYSTAL,UNIQUE_MOUNT_BATTLESPIDER_SILVER,UNIQUE_MOUNT_BATTLESPIDER_GOLD,UNIQUE_MOUNT_BATTLESPIDER_CRYSTAL,UNIQUE_MOUNT_BASTION_CRYSTAL@0,UNIQUE_MOUNT_BASTION_GOLD@0,UNIQUE_MOUNT_BASTION_SILVER@0,UNIQUE_MOUNT_RHINO_TELLAFRIEND,UNIQUE_MOUNT_GIANTSTAG_FOUNDER_EPIC';
  private readonly offHandUrl = 'T1_OFF_SHIELD,T2_OFF_SHIELD,T3_OFF_SHIELD,T4_OFF_SHIELD,T4_OFF_SHIELD@1,T4_OFF_SHIELD@2,T4_OFF_SHIELD@3,T5_OFF_SHIELD,T5_OFF_SHIELD@1,T5_OFF_SHIELD@2,T5_OFF_SHIELD@3,T6_OFF_SHIELD,T6_OFF_SHIELD@1,T6_OFF_SHIELD@2,T6_OFF_SHIELD@3,T7_OFF_SHIELD,T7_OFF_SHIELD@1,T7_OFF_SHIELD@2,T7_OFF_SHIELD@3,T8_OFF_SHIELD,T8_OFF_SHIELD@1,T8_OFF_SHIELD@2,T8_OFF_SHIELD@3,T4_OFF_TOWERSHIELD_UNDEAD,T4_OFF_TOWERSHIELD_UNDEAD@1,T4_OFF_TOWERSHIELD_UNDEAD@2,T4_OFF_TOWERSHIELD_UNDEAD@3,T5_OFF_TOWERSHIELD_UNDEAD,T5_OFF_TOWERSHIELD_UNDEAD@1,T5_OFF_TOWERSHIELD_UNDEAD@2,T5_OFF_TOWERSHIELD_UNDEAD@3,T6_OFF_TOWERSHIELD_UNDEAD,T6_OFF_TOWERSHIELD_UNDEAD@1,T6_OFF_TOWERSHIELD_UNDEAD@2,T6_OFF_TOWERSHIELD_UNDEAD@3,T7_OFF_TOWERSHIELD_UNDEAD,T7_OFF_TOWERSHIELD_UNDEAD@1,T7_OFF_TOWERSHIELD_UNDEAD@2,T7_OFF_TOWERSHIELD_UNDEAD@3,T8_OFF_TOWERSHIELD_UNDEAD,T8_OFF_TOWERSHIELD_UNDEAD@1,T8_OFF_TOWERSHIELD_UNDEAD@2,T8_OFF_TOWERSHIELD_UNDEAD@3,T4_OFF_SHIELD_HELL,T4_OFF_SHIELD_HELL@1,T4_OFF_SHIELD_HELL@2,T4_OFF_SHIELD_HELL@3,T5_OFF_SHIELD_HELL,T5_OFF_SHIELD_HELL@1,T5_OFF_SHIELD_HELL@2,T5_OFF_SHIELD_HELL@3,T6_OFF_SHIELD_HELL,T6_OFF_SHIELD_HELL@1,T6_OFF_SHIELD_HELL@2,T6_OFF_SHIELD_HELL@3,T7_OFF_SHIELD_HELL,T7_OFF_SHIELD_HELL@1,T7_OFF_SHIELD_HELL@2,T7_OFF_SHIELD_HELL@3,T8_OFF_SHIELD_HELL,T8_OFF_SHIELD_HELL@1,T8_OFF_SHIELD_HELL@2,T8_OFF_SHIELD_HELL@3,T4_OFF_SPIKEDSHIELD_MORGANA,T4_OFF_SPIKEDSHIELD_MORGANA@1,T4_OFF_SPIKEDSHIELD_MORGANA@2,T4_OFF_SPIKEDSHIELD_MORGANA@3,T5_OFF_SPIKEDSHIELD_MORGANA,T5_OFF_SPIKEDSHIELD_MORGANA@1,T5_OFF_SPIKEDSHIELD_MORGANA@2,T5_OFF_SPIKEDSHIELD_MORGANA@3,T6_OFF_SPIKEDSHIELD_MORGANA,T6_OFF_SPIKEDSHIELD_MORGANA@1,T6_OFF_SPIKEDSHIELD_MORGANA@2,T6_OFF_SPIKEDSHIELD_MORGANA@3,T7_OFF_SPIKEDSHIELD_MORGANA,T7_OFF_SPIKEDSHIELD_MORGANA@1,T7_OFF_SPIKEDSHIELD_MORGANA@2,T7_OFF_SPIKEDSHIELD_MORGANA@3,T8_OFF_SPIKEDSHIELD_MORGANA,T8_OFF_SPIKEDSHIELD_MORGANA@1,T8_OFF_SPIKEDSHIELD_MORGANA@2,T8_OFF_SPIKEDSHIELD_MORGANA@3,T4_OFF_SHIELD_AVALON,T4_OFF_SHIELD_AVALON@1,T4_OFF_SHIELD_AVALON@2,T4_OFF_SHIELD_AVALON@3,T5_OFF_SHIELD_AVALON,T5_OFF_SHIELD_AVALON@1,T5_OFF_SHIELD_AVALON@2,T5_OFF_SHIELD_AVALON@3,T6_OFF_SHIELD_AVALON,T6_OFF_SHIELD_AVALON@1,T6_OFF_SHIELD_AVALON@2,T6_OFF_SHIELD_AVALON@3,T7_OFF_SHIELD_AVALON,T7_OFF_SHIELD_AVALON@1,T7_OFF_SHIELD_AVALON@2,T7_OFF_SHIELD_AVALON@3,T8_OFF_SHIELD_AVALON,T8_OFF_SHIELD_AVALON@1,T8_OFF_SHIELD_AVALON@2,T8_OFF_SHIELD_AVALON@3,T2_OFF_BOOK,T3_OFF_BOOK,T4_OFF_BOOK,T4_OFF_BOOK@1,T4_OFF_BOOK@2,T4_OFF_BOOK@3,T5_OFF_BOOK,T5_OFF_BOOK@1,T5_OFF_BOOK@2,T5_OFF_BOOK@3,T6_OFF_BOOK,T6_OFF_BOOK@1,T6_OFF_BOOK@2,T6_OFF_BOOK@3,T7_OFF_BOOK,T7_OFF_BOOK@1,T7_OFF_BOOK@2';
  private readonly otherUrl = 'QUESTITEM_TUTORIAL_HERETIC_PLANS,QUESTITEM_TRANSFER_LETTER,QUESTITEM_LIGHT_BLUEPRINTS,QUESTITEM_LIGHT_MANUSCRIPTS,QUESTITEM_LIGHT_SURVEYS,QUESTITEM_HEAVY_MORTAR,QUESTITEM_HEAVY_CRATE,QUESTITEM_HEAVY_BARREL,QUESTITEM_LIGHT_FUR,QUESTITEM_LIGHT_THEPACKAGE,QUESTITEM_LIGHT_PATROLROUTE,QUESTITEM_HEAVY_MOONSHINE,QUESTITEM_LIGHT_KITTENS,QUESTITEM_LIGHT_BEES,QUESTITEM_LIGHT_OLDCLOTHES,QUESTITEM_HEAVY_FARMTOOLS,QUESTITEM_HEAVY_MANURE,QUESTITEM_LIGHT_ASSASSINATION,QUESTITEM_LIGHT_CASUALTIES,QUESTITEM_LIGHT_RINGS,QUESTITEM_HEAVY_MEDICAL,QUESTITEM_HEAVY_FIREBARREL,T1_TRASH,T2_TRASH,T3_TRASH,T4_TRASH,T5_TRASH,T6_TRASH,T7_TRASH,T8_TRASH';
  private readonly productUrl = 'T3_FARM_OX_GROWN,T4_FARM_OX_GROWN,T5_FARM_OX_GROWN,T6_FARM_OX_GROWN,T7_FARM_OX_GROWN,T8_FARM_OX_GROWN,T3_FARM_HORSE_GROWN,T4_FARM_HORSE_GROWN,T5_FARM_HORSE_GROWN,T6_FARM_HORSE_GROWN,T7_FARM_HORSE_GROWN,T8_FARM_HORSE_GROWN,T6_FARM_DIREWOLF_GROWN,T7_FARM_DIREBOAR_GROWN,T8_FARM_DIREBEAR_GROWN,T7_FARM_SWAMPDRAGON_GROWN,T8_FARM_MAMMOTH_GROWN,T5_FARM_COUGAR_GROWN,T8_FARM_DIREWOLF_GROWN,T4_FARM_GIANTSTAG_GROWN,T6_FARM_GIANTSTAG_GROWN,T5_FARM_MOABIRD_FW_BRIDGEWATCH_GROWN,T5_FARM_DIREBEAR_FW_FORTSTERLING_GROWN,T5_FARM_DIREBOAR_FW_LYMHURST_GROWN,T5_FARM_RAM_FW_MARTLOCK_GROWN,T5_FARM_SWAMPDRAGON_FW_THETFORD_GROWN,T3_FARM_CHICKEN_GROWN,T4_FARM_GOAT_GROWN,T5_FARM_GOOSE_GROWN,T6_FARM_SHEEP_GROWN,T7_FARM_PIG_GROWN,T8_FARM_COW_GROWN,T1_CARROT,T2_BEAN,T3_WHEAT,T4_TURNIP,T5_CABBAGE,T6_POTATO,T7_CORN,T8_PUMPKIN,T2_AGARIC,T3_COMFREY,T4_BURDOCK,T5_TEASEL,T6_FOXGLOVE,T7_MULLEIN,T8_YARROW,T3_EGG,T4_MILK,T5_EGG,T6_MILK,T8_MILK,T1_FISHCHOPS@0,T1_FISHSAUCE_LEVEL1@0,T1_FISHSAUCE_LEVEL2@0,T1_FISHSAUCE_LEVEL3@0,T1_WORM,T3_MEAT,T4_MEAT,T5_MEAT,T6_MEAT,T7_MEAT,T8_MEAT,T4_BUTTER,T6_BUTTER,T8_BUTTER,T6_ALCOHOL,T7_ALCOHOL,T8_ALCOHOL,T4_BREAD,T3_FLOUR,T2_JOURNAL_WOOD,T3_JOURNAL_WOOD,T4_JOURNAL_WOOD,T5_JOURNAL_WOOD,T6_JOURNAL_WOOD,T7_JOURNAL_WOOD,T8_JOURNAL_WOOD,T2_JOURNAL_STONE,T3_JOURNAL_STONE,T4_JOURNAL_STONE,T5_JOURNAL_STONE,T6_JOURNAL_STONE,T7_JOURNAL_STONE,T8_JOURNAL_STONE,T2_JOURNAL_ORE,T3_JOURNAL_ORE,T4_JOURNAL_ORE,T5_JOURNAL_ORE,T6_JOURNAL_ORE,T7_JOURNAL_ORE,T8_JOURNAL_ORE,T2_JOURNAL_FIBER,T3_JOURNAL_FIBER,T4_JOURNAL_FIBER,T5_JOURNAL_FIBER,T6_JOURNAL_FIBER,T7_JOURNAL_FIBER,T8_JOURNAL_FIBER,T2_JOURNAL_HIDE,T3_JOURNAL_HIDE,T4_JOURNAL_HIDE,T5_JOURNAL_HIDE,T6_JOURNAL_HIDE,T7_JOURNAL_HIDE,T8_JOURNAL_HIDE,T2_JOURNAL_WARRIOR,T3_JOURNAL_WARRIOR,T4_JOURNAL_WARRIOR,T5_JOURNAL_WARRIOR,T6_JOURNAL_WARRIOR,T7_JOURNAL_WARRIOR,T8_JOURNAL_WARRIOR,T2_JOURNAL_HUNTER,T3_JOURNAL_HUNTER,T4_JOURNAL_HUNTER,T5_JOURNAL_HUNTER,T6_JOURNAL_HUNTER,T7_JOURNAL_HUNTER,T8_JOURNAL_HUNTER';
  private readonly rangedUrl = 'T2_2H_BOW,T3_2H_BOW,T4_2H_BOW,T4_2H_BOW@1,T4_2H_BOW@2,T4_2H_BOW@3,T5_2H_BOW,T5_2H_BOW@1,T5_2H_BOW@2,T5_2H_BOW@3,T6_2H_BOW,T6_2H_BOW@1,T6_2H_BOW@2,T6_2H_BOW@3,T7_2H_BOW,T7_2H_BOW@1,T7_2H_BOW@2,T7_2H_BOW@3,T8_2H_BOW,T8_2H_BOW@1,T8_2H_BOW@2,T8_2H_BOW@3,T4_2H_WARBOW,T4_2H_WARBOW@1,T4_2H_WARBOW@2,T4_2H_WARBOW@3,T5_2H_WARBOW,T5_2H_WARBOW@1,T5_2H_WARBOW@2,T5_2H_WARBOW@3,T6_2H_WARBOW,T6_2H_WARBOW@1,T6_2H_WARBOW@2,T6_2H_WARBOW@3,T7_2H_WARBOW,T7_2H_WARBOW@1,T7_2H_WARBOW@2,T7_2H_WARBOW@3,T8_2H_WARBOW,T8_2H_WARBOW@1,T8_2H_WARBOW@2,T8_2H_WARBOW@3,T4_2H_LONGBOW,T4_2H_LONGBOW@1,T4_2H_LONGBOW@2,T4_2H_LONGBOW@3,T5_2H_LONGBOW,T5_2H_LONGBOW@1,T5_2H_LONGBOW@2,T5_2H_LONGBOW@3,T6_2H_LONGBOW,T6_2H_LONGBOW@1,T6_2H_LONGBOW@2,T6_2H_LONGBOW@3,T7_2H_LONGBOW,T7_2H_LONGBOW@1,T7_2H_LONGBOW@2,T7_2H_LONGBOW@3,T8_2H_LONGBOW,T8_2H_LONGBOW@1,T8_2H_LONGBOW@2,T8_2H_LONGBOW@3,T4_2H_LONGBOW_UNDEAD,T4_2H_LONGBOW_UNDEAD@1,T4_2H_LONGBOW_UNDEAD@2,T4_2H_LONGBOW_UNDEAD@3,T5_2H_LONGBOW_UNDEAD,T5_2H_LONGBOW_UNDEAD@1,T5_2H_LONGBOW_UNDEAD@2,T5_2H_LONGBOW_UNDEAD@3,T6_2H_LONGBOW_UNDEAD,T6_2H_LONGBOW_UNDEAD@1,T6_2H_LONGBOW_UNDEAD@2,T6_2H_LONGBOW_UNDEAD@3,T7_2H_LONGBOW_UNDEAD,T7_2H_LONGBOW_UNDEAD@1,T7_2H_LONGBOW_UNDEAD@2,T7_2H_LONGBOW_UNDEAD@3,T8_2H_LONGBOW_UNDEAD,T8_2H_LONGBOW_UNDEAD@1,T8_2H_LONGBOW_UNDEAD@2,T8_2H_LONGBOW_UNDEAD@3,T4_2H_BOW_HELL,T4_2H_BOW_HELL@1,T4_2H_BOW_HELL@2,T4_2H_BOW_HELL@3,T5_2H_BOW_HELL,T5_2H_BOW_HELL@1,T5_2H_BOW_HELL@2,T5_2H_BOW_HELL@3,T6_2H_BOW_HELL,T6_2H_BOW_HELL@1,T6_2H_BOW_HELL@2,T6_2H_BOW_HELL@3,T7_2H_BOW_HELL,T7_2H_BOW_HELL@1,T7_2H_BOW_HELL@2,T7_2H_BOW_HELL@3,T8_2H_BOW_HELL,T8_2H_BOW_HELL@1,T8_2H_BOW_HELL@2,T8_2H_BOW_HELL@3,T4_2H_BOW_KEEPER,T4_2H_BOW_KEEPER@1,T4_2H_BOW_KEEPER@2,T4_2H_BOW_KEEPER@3,T5_2H_BOW_KEEPER,T5_2H_BOW_KEEPER@1,T5_2H_BOW_KEEPER@2,T5_2H_BOW_KEEPER@3,T6_2H_BOW_KEEPER,T6_2H_BOW_KEEPER@1,T6_2H_BOW_KEEPER@2,T6_2H_BOW_KEEPER@3,T7_2H_BOW_KEEPER,T7_2H_BOW_KEEPER@1,T7_2H_BOW_KEEPER@2,T7_2H_BOW_KEEPER@3,T8_2H_BOW_KEEPER,T8_2H_BOW_KEEPER@1';
  private readonly resourcesUrl = 'T1_WOOD,T2_WOOD,T3_WOOD,T4_WOOD,T5_WOOD,T6_WOOD,T7_WOOD,T8_WOOD,T4_WOOD_LEVEL1@1,T5_WOOD_LEVEL1@1,T6_WOOD_LEVEL1@1,T7_WOOD_LEVEL1@1,T8_WOOD_LEVEL1@1,T4_WOOD_LEVEL2@2,T5_WOOD_LEVEL2@2,T6_WOOD_LEVEL2@2,T7_WOOD_LEVEL2@2,T8_WOOD_LEVEL2@2,T4_WOOD_LEVEL3@3,T5_WOOD_LEVEL3@3,T6_WOOD_LEVEL3@3,T7_WOOD_LEVEL3@3,T8_WOOD_LEVEL3@3,T1_ROCK,T2_ROCK,T3_ROCK,T4_ROCK,T5_ROCK,T6_ROCK,T7_ROCK,T8_ROCK,T4_ROCK_LEVEL1@1,T5_ROCK_LEVEL1@1,T6_ROCK_LEVEL1@1,T7_ROCK_LEVEL1@1,T8_ROCK_LEVEL1@1,T4_ROCK_LEVEL2@2,T5_ROCK_LEVEL2@2,T6_ROCK_LEVEL2@2,T7_ROCK_LEVEL2@2,T8_ROCK_LEVEL2@2,T4_ROCK_LEVEL3@3,T5_ROCK_LEVEL3@3,T6_ROCK_LEVEL3@3,T7_ROCK_LEVEL3@3,T8_ROCK_LEVEL3@3,T2_ORE,T3_ORE,T4_ORE,T5_ORE,T6_ORE,T7_ORE,T8_ORE,T4_ORE_LEVEL1@1,T5_ORE_LEVEL1@1,T6_ORE_LEVEL1@1,T7_ORE_LEVEL1@1,T8_ORE_LEVEL1@1,T4_ORE_LEVEL2@2,T5_ORE_LEVEL2@2,T6_ORE_LEVEL2@2,T7_ORE_LEVEL2@2,T8_ORE_LEVEL2@2,T4_ORE_LEVEL3@3,T5_ORE_LEVEL3@3,T6_ORE_LEVEL3@3,T7_ORE_LEVEL3@3,T8_ORE_LEVEL3@3,T1_HIDE,T2_HIDE,T3_HIDE,T4_HIDE,T5_HIDE,T6_HIDE,T7_HIDE,T8_HIDE,T4_HIDE_LEVEL1@1,T5_HIDE_LEVEL1@1,T6_HIDE_LEVEL1@1,T7_HIDE_LEVEL1@1,T8_HIDE_LEVEL1@1,T4_HIDE_LEVEL2@2,T5_HIDE_LEVEL2@2,T6_HIDE_LEVEL2@2,T7_HIDE_LEVEL2@2,T8_HIDE_LEVEL2@2,T4_HIDE_LEVEL3@3,T5_HIDE_LEVEL3@3,T6_HIDE_LEVEL3@3,T7_HIDE_LEVEL3@3,T8_HIDE_LEVEL3@3,T2_FIBER,T3_FIBER,T4_FIBER,T5_FIBER,T6_FIBER,T7_FIBER,T8_FIBER,T4_FIBER_LEVEL1@1,T5_FIBER_LEVEL1@1,T6_FIBER_LEVEL1@1,T7_FIBER_LEVEL1@1,T8_FIBER_LEVEL1@1,T4_FIBER_LEVEL2@2,T5_FIBER_LEVEL2@2,T6_FIBER_LEVEL2@2,T7_FIBER_LEVEL2@2,T8_FIBER_LEVEL2@2,T4_FIBER_LEVEL3@3,T5_FIBER_LEVEL3@3,T6_FIBER_LEVEL3@3,T7_FIBER_LEVEL3@3,T8_FIBER_LEVEL3@3,T2_PLANKS,T3_PLANKS,T4_PLANKS,T5_PLANKS,T6_PLANKS,T7_PLANKS,T8_PLANKS';
  private readonly tokenUrl = 'QUESTITEM_CARAVAN_TRADEPACK_SWAMP_LIGHT@0,QUESTITEM_CARAVAN_TRADEPACK_SWAMP_MEDIUM@0,QUESTITEM_CARAVAN_TRADEPACK_SWAMP_HEAVY@0,QUESTITEM_CARAVAN_TRADEPACK_FOREST_LIGHT@0,QUESTITEM_CARAVAN_TRADEPACK_FOREST_MEDIUM@0,QUESTITEM_CARAVAN_TRADEPACK_FOREST_HEAVY@0,QUESTITEM_CARAVAN_TRADEPACK_STEPPE_LIGHT@0,QUESTITEM_CARAVAN_TRADEPACK_STEPPE_MEDIUM@0,QUESTITEM_CARAVAN_TRADEPACK_STEPPE_HEAVY@0,QUESTITEM_CARAVAN_TRADEPACK_HIGHLAND_LIGHT@0,QUESTITEM_CARAVAN_TRADEPACK_HIGHLAND_MEDIUM@0,QUESTITEM_CARAVAN_TRADEPACK_HIGHLAND_HEAVY@0,QUESTITEM_CARAVAN_TRADEPACK_MOUNTAIN_LIGHT@0,QUESTITEM_CARAVAN_TRADEPACK_MOUNTAIN_MEDIUM@0,QUESTITEM_CARAVAN_TRADEPACK_MOUNTAIN_HEAVY@0,QUESTITEM_TOKEN_ARENA_UNRANKED,QUESTITEM_EXP_TOKEN_D1_T6_EXP_HRD_WINTER_EVENT@0,QUESTITEM_EXP_TOKEN_D1_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D2_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D3_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D4_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D5_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D6_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D7_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D8_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D9_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D10_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D11_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D12_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D13_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D14_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D15_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D16_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D17_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D18_T6_EXP_HRD_UNDEAD_RECRUITMENT@0,QUESTITEM_EXP_TOKEN_D1_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D2_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D3_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D4_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D5_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D6_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D7_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D8_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D9_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D10_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D11_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D12_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D13_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D14_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D15_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D16_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D17_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D18_T6_EXP_HRD_HERETIC_FISHYBUSINESS@0,QUESTITEM_EXP_TOKEN_D1_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D2_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D3_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D4_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D5_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D6_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D7_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D8_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D9_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D10_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D11_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D12_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D13_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D14_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D15_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D16_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D17_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D18_T6_EXP_HRD_KEEPER_STONEWARS@0,QUESTITEM_EXP_TOKEN_D1_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D2_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D3_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D4_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D5_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D6_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D7_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D8_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D9_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D10_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D11_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D12_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D13_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D14_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D15_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D16_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D17_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D18_T6_EXP_HRD_HERETIC_LUMBERCAMP@0,QUESTITEM_EXP_TOKEN_D1_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D2_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D3_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D4_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D5_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D6_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D7_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D8_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D9_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D10_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D11_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D12_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D13_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D14_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D15_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D16_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D17_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D18_T6_EXP_HRD_UNDEAD_SEWERSCRYPT@0,QUESTITEM_EXP_TOKEN_D1_T6_EXP_HRD_KEEPER_MUSHROOM@0,QUESTITEM_EXP_TOKEN_D2_T6_EXP_HRD_KEEPER_MUSHROOM@0,QUESTITEM_EXP_TOKEN_D3_T6_EXP_HRD_KEEPER_MUSHROOM@0,QUESTITEM_EXP_TOKEN_D4_T6_EXP_HRD_KEEPER_MUSHROOM@0,QUESTITEM_EXP_TOKEN_D5_T6_EXP_HRD_KEEPER_MUSHROOM@0,QUESTITEM_EXP_TOKEN_D6_T6_EXP_HRD_KEEPER_MUSHROOM@0,QUESTITEM_EXP_TOKEN_D7_T6_EXP_HRD_KEEPER_MUSHROOM@0,QUESTITEM_EXP_TOKEN_D8_T6_EXP_HRD_KEEPER_MUSHROOM@0,QUESTITEM_EXP_TOKEN_D9_T6_EXP_HRD_KEEPER_MUSHROOM@0,QUESTITEM_EXP_TOKEN_D10_T6_EXP_HRD_KEEPER_MUSHROOM@0,QUESTITEM_EXP_TOKEN_D11_T6_EXP_HRD_KEEPER_MUSHROOM@0,QUESTITEM_EXP_TOKEN_D12_T6_EXP_HRD_KEEPER_MUSHROOM@0,QUESTITEM_EXP_TOKEN_D13_T6_EXP_HRD_KEEPER_MUSHROOM@0';
  private readonly toolUrl = 'T1_2H_TOOL_PICK,T2_2H_TOOL_PICK,T3_2H_TOOL_PICK,T4_2H_TOOL_PICK,T5_2H_TOOL_PICK,T6_2H_TOOL_PICK,T7_2H_TOOL_PICK,T8_2H_TOOL_PICK,T4_2H_TOOL_PICK_AVALON,T5_2H_TOOL_PICK_AVALON,T6_2H_TOOL_PICK_AVALON,T7_2H_TOOL_PICK_AVALON,T8_2H_TOOL_PICK_AVALON,T1_2H_TOOL_HAMMER,T2_2H_TOOL_HAMMER,T3_2H_TOOL_HAMMER,T4_2H_TOOL_HAMMER,T5_2H_TOOL_HAMMER,T6_2H_TOOL_HAMMER,T7_2H_TOOL_HAMMER,T8_2H_TOOL_HAMMER,T4_2H_TOOL_HAMMER_AVALON,T5_2H_TOOL_HAMMER_AVALON,T6_2H_TOOL_HAMMER_AVALON,T7_2H_TOOL_HAMMER_AVALON,T8_2H_TOOL_HAMMER_AVALON,T1_2H_TOOL_AXE,T2_2H_TOOL_AXE,T3_2H_TOOL_AXE,T4_2H_TOOL_AXE,T5_2H_TOOL_AXE,T6_2H_TOOL_AXE,T7_2H_TOOL_AXE,T8_2H_TOOL_AXE,T4_2H_TOOL_AXE_AVALON,T5_2H_TOOL_AXE_AVALON,T6_2H_TOOL_AXE_AVALON,T7_2H_TOOL_AXE_AVALON,T8_2H_TOOL_AXE_AVALON,T1_2H_TOOL_SICKLE,T2_2H_TOOL_SICKLE,T3_2H_TOOL_SICKLE,T4_2H_TOOL_SICKLE,T5_2H_TOOL_SICKLE,T6_2H_TOOL_SICKLE,T7_2H_TOOL_SICKLE,T8_2H_TOOL_SICKLE,T4_2H_TOOL_SICKLE_AVALON,T5_2H_TOOL_SICKLE_AVALON,T6_2H_TOOL_SICKLE_AVALON,T7_2H_TOOL_SICKLE_AVALON,T8_2H_TOOL_SICKLE_AVALON,T1_2H_TOOL_KNIFE,T2_2H_TOOL_KNIFE,T3_2H_TOOL_KNIFE,T4_2H_TOOL_KNIFE,T5_2H_TOOL_KNIFE,T6_2H_TOOL_KNIFE,T7_2H_TOOL_KNIFE,T8_2H_TOOL_KNIFE,T4_2H_TOOL_KNIFE_AVALON,T5_2H_TOOL_KNIFE_AVALON,T6_2H_TOOL_KNIFE_AVALON,T7_2H_TOOL_KNIFE_AVALON,T8_2H_TOOL_KNIFE_AVALON,T2_2H_TOOL_SIEGEHAMMER,T3_2H_TOOL_SIEGEHAMMER,T4_2H_TOOL_SIEGEHAMMER,T5_2H_TOOL_SIEGEHAMMER,T6_2H_TOOL_SIEGEHAMMER,T7_2H_TOOL_SIEGEHAMMER,T8_2H_TOOL_SIEGEHAMMER,T4_2H_TOOL_SIEGEHAMMER_AVALON,T5_2H_TOOL_SIEGEHAMMER_AVALON,T6_2H_TOOL_SIEGEHAMMER_AVALON,T7_2H_TOOL_SIEGEHAMMER_AVALON,T8_2H_TOOL_SIEGEHAMMER_AVALON,T3_2H_TOOL_FISHINGROD,T4_2H_TOOL_FISHINGROD,T5_2H_TOOL_FISHINGROD,T6_2H_TOOL_FISHINGROD,T7_2H_TOOL_FISHINGROD,T8_2H_TOOL_FISHINGROD,T4_2H_TOOL_FISHINGROD_AVALON,T5_2H_TOOL_FISHINGROD_AVALON,T6_2H_TOOL_FISHINGROD_AVALON,T7_2H_TOOL_FISHINGROD_AVALON,T8_2H_TOOL_FISHINGROD_AVALON';
  private readonly trophiesUrl = 'UNIQUE_FURNITUREITEM_FOUNDER_LOOKINGGLASS,T2_FURNITUREITEM_TROPHY_GENERAL,T3_FURNITUREITEM_TROPHY_GENERAL,T4_FURNITUREITEM_TROPHY_GENERAL,T5_FURNITUREITEM_TROPHY_GENERAL,T6_FURNITUREITEM_TROPHY_GENERAL,T7_FURNITUREITEM_TROPHY_GENERAL,T8_FURNITUREITEM_TROPHY_GENERAL,T8_FURNITUREITEM_TROPHY_FISHING_BOSS,T2_FURNITUREITEM_TROPHY_MERCENARY,T3_FURNITUREITEM_TROPHY_MERCENARY,T4_FURNITUREITEM_TROPHY_MERCENARY,T5_FURNITUREITEM_TROPHY_MERCENARY,T6_FURNITUREITEM_TROPHY_MERCENARY,T7_FURNITUREITEM_TROPHY_MERCENARY,T8_FURNITUREITEM_TROPHY_MERCENARY,T2_FURNITUREITEM_TROPHY_HIDE,T3_FURNITUREITEM_TROPHY_HIDE,T4_FURNITUREITEM_TROPHY_HIDE,T5_FURNITUREITEM_TROPHY_HIDE,T6_FURNITUREITEM_TROPHY_HIDE,T7_FURNITUREITEM_TROPHY_HIDE,T8_FURNITUREITEM_TROPHY_HIDE,T2_FURNITUREITEM_TROPHY_ORE,T3_FURNITUREITEM_TROPHY_ORE,T4_FURNITUREITEM_TROPHY_ORE,T5_FURNITUREITEM_TROPHY_ORE,T6_FURNITUREITEM_TROPHY_ORE,T7_FURNITUREITEM_TROPHY_ORE,T8_FURNITUREITEM_TROPHY_ORE,T2_FURNITUREITEM_TROPHY_FIBER,T3_FURNITUREITEM_TROPHY_FIBER,T4_FURNITUREITEM_TROPHY_FIBER,T5_FURNITUREITEM_TROPHY_FIBER,T6_FURNITUREITEM_TROPHY_FIBER,T7_FURNITUREITEM_TROPHY_FIBER,T8_FURNITUREITEM_TROPHY_FIBER,T2_FURNITUREITEM_TROPHY_ROCK,T3_FURNITUREITEM_TROPHY_ROCK,T4_FURNITUREITEM_TROPHY_ROCK,T5_FURNITUREITEM_TROPHY_ROCK,T6_FURNITUREITEM_TROPHY_ROCK,T7_FURNITUREITEM_TROPHY_ROCK,T8_FURNITUREITEM_TROPHY_ROCK,T2_FURNITUREITEM_TROPHY_WOOD,T3_FURNITUREITEM_TROPHY_WOOD,T4_FURNITUREITEM_TROPHY_WOOD,T5_FURNITUREITEM_TROPHY_WOOD,T6_FURNITUREITEM_TROPHY_WOOD,T7_FURNITUREITEM_TROPHY_WOOD,T8_FURNITUREITEM_TROPHY_WOOD,T2_FURNITUREITEM_TROPHY_FISH,T3_FURNITUREITEM_TROPHY_FISH,T4_FURNITUREITEM_TROPHY_FISH,T5_FURNITUREITEM_TROPHY_FISH,T6_FURNITUREITEM_TROPHY_FISH,T7_FURNITUREITEM_TROPHY_FISH,T8_FURNITUREITEM_TROPHY_FISH';

  private itemsIdMap: Map<string, string>;

  constructor(
    private readonly httpClient: HttpClient
  ) {}

  ngOnInit(): void {
    this.initItemsIdMap();
    this.observeFilterByLocation();
  }

  onButtonClick(): void {
    if (this.isLoading) {
      return;
    }
    if (!this.searchForm.value.silver) {
      this.searchForm.controls.silver.patchValue(100000000);
    }
    this.isLoading = true;
    this.fetchResults();
  }

  private fetchResults(): void {
    const url = this.baseUrl + this.getSelectedItemTypeUrl();
    this.httpClient.get<Item[]>(url)
      .subscribe(items => {
        this.isLoading = false;
        this.results = new MatTableDataSource(this.evaluateResults(items));
        this.results.sort = this.sort;
        this.results.paginator = this.paginator;
      });
  }

  private getSelectedItemTypeUrl(): string {
    const selectedItemType: ItemType = this.searchForm.value.itemType;
    switch (selectedItemType) {
      case ItemType.Farmable:
        return this.farmableUrl;
      case ItemType.Forniture:
        return this.fornitureUrl;
      case ItemType.GatheringGear:
        return this.gatheringGearUrl;
      case ItemType.LuxuryGoods:
        return this.luxuryGoodsUrl;
      case ItemType.Magic:
        return this.magicUrl;
      case ItemType.Materials:
        return this.materialsUrl;
      case ItemType.Melee:
        return this.meleeUrl;
      case ItemType.Mount:
        return this.mountUrl;
      case ItemType.OffHand:
        return this.offHandUrl;
      case ItemType.Other:
        return this.otherUrl;
      case ItemType.Product:
        return this.productUrl;
      case ItemType.Ranged:
        return this.rangedUrl;
      case ItemType.Resources:
        return this.resourcesUrl;
      case ItemType.Token:
        return this.tokenUrl;
      case ItemType.Tool:
        return this.toolUrl;
      case ItemType.Trophies:
        return this.trophiesUrl;
      case ItemType.Accessories:
        return this.accessoriesUrl;
      case ItemType.Armors:
        return this.armorsUrl;
      case ItemType.Artefacts:
        return this.artefactsUrl;
      case ItemType.CityResources:
        return this.cityResourcesUrl;
      case ItemType.Consumables:
        return this.consumablesUrl;
    }
  }

  private evaluateResults(items: Item[]): Result[] {
    const formValue = this.searchForm.value;
    const maxTotSilver = formValue.silver;
    const filterByLocation = formValue.filterByLocation;
    const groupedByItemId = _.groupBy(items, 'item_id');
    const ranking: Result[] = [];
    Object.keys(groupedByItemId).forEach(itemId => {
      const entries = groupedByItemId[itemId];
      let currentHighestBuyPrice: Item;
      let currentLowestSell: Item;
      entries.forEach(entry => {
        const entryBuyPriceMax = entry.buy_price_max;
        const isEntryBuyPriceMaxAcceptable = entryBuyPriceMax > 0 &&
          (!currentHighestBuyPrice || entryBuyPriceMax > currentHighestBuyPrice.buy_price_max) &&
          (!filterByLocation || formValue.sellAt === entry.city);
        if (isEntryBuyPriceMaxAcceptable) {
          currentHighestBuyPrice = entry;
        }
        const entrySellPriceMin = entry.sell_price_min;
        const isEntrySellPriceMinAcceptable = entrySellPriceMin > 0 &&
          entrySellPriceMin <= maxTotSilver &&
          (!currentLowestSell || entrySellPriceMin < currentLowestSell.sell_price_min) &&
          (!filterByLocation || formValue.buyAt === entry.city);
        if (isEntrySellPriceMinAcceptable) {
          currentLowestSell = entry;
        }
      });
      if (!currentHighestBuyPrice || !currentLowestSell) {
        return;
      }
      const sellPriceMin = currentLowestSell.sell_price_min;
      const profit = currentHighestBuyPrice.buy_price_max - sellPriceMin;
      if (profit <= 0) {
        return;
      }
      const name = this.itemsIdMap.get(currentLowestSell.item_id);
      ranking.push({
        buy: {...currentLowestSell, name},
        sell: {...currentHighestBuyPrice, name},
        profit,
        profitPerc: profit / sellPriceMin * 100
      });
    });
    return _.sortBy(ranking, 'profitPerc').reverse();
  }

  private observeFilterByLocation(): void {
    const filterByLocationControl = this.searchForm.controls.filterByLocation;
    filterByLocationControl.valueChanges
      .pipe(distinctUntilChanged())
      .subscribe(filterByLocation => {
        if (filterByLocation) {
          this.searchForm.controls.buyAt.enable();
          this.searchForm.controls.sellAt.enable();
        } else {
          this.searchForm.controls.buyAt.disable();
          this.searchForm.controls.sellAt.disable();
        }
      });
  }

  private initItemsIdMap(): void {
    this.httpClient.get<any[]>('assets/items.json')
      .pipe(
        map(items => {
          const itemsIdMap = new Map<string, string>();
          items.forEach(item => {
            itemsIdMap.set(item.UniqueName, item?.LocalizedNames ? item.LocalizedNames['EN-US'] : '');
          });
          return itemsIdMap;
        })
      ).subscribe(data => this.itemsIdMap = data);
  }
}
